import asyncio
import base64
import io
import json
import logging
import os
import random
from collections import deque
from concurrent.futures import ThreadPoolExecutor
from datetime import datetime
from typing import Deque, List, Optional, Tuple, Dict, Any

import redis.asyncio as redis
import unify
import cv2
import numpy as np
from PIL import Image
from skimage.metrics import structural_similarity as ssim

from unity.conversation_manager_2.event_broker import get_event_broker
from unity.image_manager.image_manager import ImageManager
from unity.transcript_manager.transcript_manager import TranscriptManager
from unity.transcript_manager.types.message import (
    Medium,
    Message,
    ScreenShareAnnotation,
)

from .prompt_builders import build_summary_update_prompt, build_turn_analysis_prompt
from .types import KeyEvent, TurnAnalysisResponse

logger = logging.getLogger(__name__)


class ScreenShareManager:
    """
    A background service that analyzes screen share streams and user speech to
    detect and annotate key events, feeding context to both the live
    ConversationManager and the historical TranscriptManager.

    How It Works
    ------------
    The manager operates by listening to a Redis event stream for two main types
    of events: `app:comms:screen_frame` for video frames and
    `app:comms:phone_utterance` for user speech. It processes these events
    asynchronously to build a comprehensive narrative of the user's actions.

    1. Three-Stage Vision Event Detection:
       To accurately detect meaningful UI changes while filtering out noise like
       cursor movements or minor animations, a three-stage pipeline is used for
       every new frame:
       a. MSE Pre-filter: A cheap Mean Squared Error check on downsampled,
          grayscale images quickly discards frames with no significant pixel change.
       b. SSIM Perceptual Check: If MSE detects a change, a more accurate but
          CPU-intensive Structural Similarity Index (SSIM) check is performed
          to verify the change is perceptually significant.
       c. Semantic Contour Analysis: If SSIM also confirms a difference, a final
          semantic filter is applied. This uses OpenCV to find the contours
          (outlines) of all changed regions and filters them based on size and
          shape. This step effectively ignores noise like thin scrollbars or
          small cursors. A "vision event" is created only if a change passes
          all three stages.

    2. Speech Event Handling & Debouncing:
       - When a user speaks, a `phone_utterance` event is received.
       - This event triggers a "turn analysis," but not immediately. A short
         debounce window is used to group rapid, successive events (e.g.,
         multiple clicks while speaking) into a single analysis call.
       - This reduces LLM costs and API calls, improving overall efficiency.

    3. Broader Context Tracking:
       - Each event analysis receives as extra context (a) a rolling summary of the session,
         generated by a separate summary worker, and (b) the lastest 5 events since the event

    4. Decoupled Architecture (Analysis vs. Logging):
       - The `_analyze_turn` method performs the quick task of gathering context
         and calling the LLM. It then places the results into a bounded `_logging_queue`.
       - A separate `_logging_worker` pulls from this queue to handle slow I/O,
         such as uploading images (with retries) and persisting the transcript message.
       - This ensures the manager is always ready to process new screen or speech
         events without getting blocked by network latency from previous events.

    Event Processing Scenarios
    --------------------------
    The manager is designed to handle three primary scenarios to ensure all
    actions are captured accurately:

    - Scenario 1: Speech and Vision Events Occur Together
      When a user speaks while interacting with the screen (e.g., "I'll click
      this button"), the utterance triggers an analysis that includes both the
      speech content and the visual evidence of the click. The Language Model (LLM)
      receives this combined context and generates a rich `KeyEvent` that links
      the action to the speech.

    - Scenario 2: Only Speech Events Occur
      If the user speaks without performing a visual action, the utterance still
      triggers an analysis. The LLM processes the speech to identify the user's
      intent, and this is logged to the transcript without a corresponding visual.

    - Scenario 3: Only Vision Events Occur (Silent Actions)
      If the user performs an action without speaking (e.g., clicking a link),
      the visual change is detected and stored as a pending vision event. If no
      speech occurs within an inactivity timeout (INACTIVITY_TIMEOUT_SEC), the
      manager "flushes" these pending events, sending them to the LLM for analysis.
      The resulting `KeyEvents` are temporarily stored in `_stored_silent_key_events`.
      They are then merged with the events from the *next* speech utterance,
      ensuring that the context of the silent action is not lost and is logged
      alongside the user's subsequent thoughts.

    Semantic Association (`[x:y]` Notation)
    ---------------------------------------
    A key feature is the ability to semantically link a visual event (a screenshot)
    to the exact words the user spoke. This is achieved via the `triggering_phrase`
    identified by the LLM.

    - The LLM is prompted to find the specific text span in the user's speech
      that corresponds to a visual action (e.g., for a click on a "Submit" button,
      the triggering phrase might be "click this").
    - In the `_log_turn_to_transcript` method, if a `KeyEvent` contains this
      `triggering_phrase`, the code searches for the phrase in the full speech
      content to find its start and end character indices.
    - It then creates a mapping in the format `{'[start:end]': image_id}`.
    - This mapping is stored in the `images` field of the `Message` object,
      creating a durable, precise link between the user's words and their actions.
      This association is only created when speech and vision events are analyzed
      together.

    Architecture for Parallelism
    ----------------------------
    To handle a high volume of frames concurrently without errors, this manager
    uses a Sequencer Pattern, separating parallel computation from serial state updates.

    1.  **Producer (Event Listener)**: The main `_listen_for_events` loop is the
        producer. It receives raw frame data, tags it with a unique, monotonically
        increasing `sequence_id`, and places `(sequence_id, event_data)` onto
        the `_frame_queue`. It also implements adaptive frame dropping: if the queue
        is over 75% full, it proactively drops frames to prevent being overwhelmed.

    2.  **Concurrent Workers (Computation)**: A pool of `_frame_processing_worker`
        tasks (size determined by `MAX_FRAME_WORKERS`) act as consumers. They pull
        items from the `_frame_queue` and perform the slow, CPU-intensive image
        analysis (decoding and comparisons). Crucially, these workers are stateless;
        they do not read or modify the shared screen state. Once done, they place
        their result, tagged with the original `sequence_id`, onto a second queue:
        `_results_queue`.

    3.  **Sequencer (State Management)**: A single, dedicated `_sequencer_task` is
        the only part of the system authorized to modify the screen state. It reads
        results from the `_results_queue`. Because workers may finish out of order,
        the sequencer buffers incoming results and processes them only when it has
        the next expected `sequence_id`. This guarantees that frames are compared
        chronologically, eliminating race conditions and ensuring logical consistency.
        It is this task that updates `_last_significant_frame_b64` and creates
        `pending_vision_events`.
    """

    def __init__(self):
        # Configuration
        self.MSE_THRESHOLD = 100
        self.SSIM_THRESHOLD = 0.80
        self.MIN_CONTOUR_AREA = 100
        self.MAX_ASPECT_RATIO = 20
        self.DEBOUNCE_DELAY_SEC = 0.5
        self.INACTIVITY_TIMEOUT_SEC = 5.0
        self.FRAME_BUFFER_SIZE = 100
        self.MAX_FRAME_WORKERS = os.cpu_count() or 4
        self.FRAME_QUEUE_SIZE = 150
        self.RESULTS_QUEUE_SIZE = 200
        self.LOGGING_QUEUE_SIZE = 50
        self.VISUAL_EVENT_SAMPLING_THRESHOLD = 3
        self.BURST_DETECTION_THRESHOLD_SEC = 1.0
        self.MAX_CONCURRENT_LOGGING_TASKS = 5
        self.IMAGE_UPLOAD_MAX_RETRIES = 3
        self.IMAGE_UPLOAD_INITIAL_BACKOFF = 1.0
        self.ADAPTIVE_DROP_THRESHOLD = 0.75

        # Clients and Managers
        self._event_broker: redis.Redis = get_event_broker()
        self._analysis_client = unify.AsyncUnify(
            "gpt-4o@openai",
            response_format=TurnAnalysisResponse,
        )
        self._summary_client = unify.AsyncUnify("gpt-4o-mini@openai")
        self._image_manager = ImageManager()
        self._transcript_manager = TranscriptManager()
        self._cpu_executor = ThreadPoolExecutor(max_workers=os.cpu_count() or 4)

        # State Variables
        self._stop_event = asyncio.Event()
        self._frame_sequence_id = 0
        self._frame_queue = asyncio.Queue(maxsize=self.FRAME_QUEUE_SIZE)
        self._results_queue = asyncio.Queue(maxsize=self.RESULTS_QUEUE_SIZE)
        self._frame_workers: List[asyncio.Task] = []
        self._sequencer_task: Optional[asyncio.Task] = None
        self._frame_buffer: Deque[Tuple[float, str]] = deque(
            maxlen=self.FRAME_BUFFER_SIZE,
        )
        self._pending_vision_events: List[Dict] = []
        self._stored_silent_key_events: List[KeyEvent] = []
        self._stored_silent_frame_map: Dict[float, str] = {}
        self._last_significant_frame_b64: Optional[str] = None
        self._last_significant_frame_pil: Optional[Image.Image] = None
        self._last_user_utterance_message_id: Optional[int] = None
        self._last_activity_time: float = asyncio.get_event_loop().time()
        self._state_lock = asyncio.Lock()
        self._analyses_in_flight = 0
        self._logging_queue = asyncio.Queue(maxsize=self.LOGGING_QUEUE_SIZE)
        self._logging_semaphore = asyncio.Semaphore(self.MAX_CONCURRENT_LOGGING_TASKS)
        self._dispatcher_task: Optional[asyncio.Task] = None
        self._debounce_task: Optional[asyncio.Task] = None

        # State for rolling summary and recent events
        self._session_summary: str = "The session has just begun."
        self._recent_key_events: Deque[KeyEvent] = deque(maxlen=5)
        self._unsummarized_events: List[KeyEvent] = []
        self._summary_update_lock = asyncio.Lock()
        self._summary_update_task: Optional[asyncio.Task] = None

    def set_session_context(self, context_text: str):
        """
        Sets the initial context for the screen share session. This should be
        called before any events are processed to prime the analysis LLM.
        """
        if not context_text or not isinstance(context_text, str):
            logger.warning("Invalid session context provided. Ignoring.")
            return

        logger.info(f"Setting initial session context to: '{context_text}'")

        async def update_summary():
            async with self._state_lock:
                self._session_summary = context_text.strip()

        try:
            loop = asyncio.get_running_loop()
            if loop.is_running():
                asyncio.create_task(update_summary())
            else:
                loop.run_until_complete(update_summary())
        except RuntimeError:
            asyncio.run(update_summary())

    async def start(self):
        """Starts the main event listening and the logging dispatcher."""
        logger.info("ScreenShareManager started. Initializing background tasks...")
        self._dispatcher_task = asyncio.create_task(self._logging_dispatcher())
        self._sequencer_task = asyncio.create_task(self._sequencer())
        self._frame_workers = [
            asyncio.create_task(self._frame_processing_worker())
            for _ in range(self.MAX_FRAME_WORKERS)
        ]
        await self._listen_for_events()

    def stop(self):
        """Signals the manager to gracefully shut down."""
        self._stop_event.set()
        if self._dispatcher_task and not self._dispatcher_task.done():
            self._dispatcher_task.cancel()
        if self._sequencer_task and not self._sequencer_task.done():
            self._sequencer_task.cancel()
        for worker in self._frame_workers:
            if not worker.done():
                worker.cancel()
        if self._summary_update_task and not self._summary_update_task.done():
            self._summary_update_task.cancel()
        if self._debounce_task and not self._debounce_task.done():
            self._debounce_task.cancel()
        self._cpu_executor.shutdown(wait=False)
        logger.info("ScreenShareManager stopping...")

    def _b64_to_image(self, b64_string: str) -> Image.Image:
        """Converts a base64 data URL to a resized, grayscale PIL Image."""
        try:
            img_data = base64.b64decode(b64_string.split(",")[1])
            img = Image.open(io.BytesIO(img_data)).convert("L").resize((512, 288))
            return img
        except Exception as e:
            logger.warning(
                "Failed to decode or process base64 image string.", exc_info=True
            )
            raise ValueError("Invalid base64 image data") from e

    def _calculate_mse(self, img1: Image.Image, img2: Image.Image) -> float:
        """Calculates the Mean Squared Error between two images."""
        err = np.sum(
            (np.array(img1).astype("float") - np.array(img2).astype("float")) ** 2
        )
        err /= float(img1.size[0] * img1.size[1])
        return err

    def _is_semantically_significant(
        self, img_before: Image.Image, img_after: Image.Image
    ) -> bool:
        """
        Performs a semantic check on the visual change by analyzing the contours
        of the difference between two frames. It filters out noise like cursors
        or small, irrelevant artifacts.
        """
        cv_before, cv_after = np.array(img_before), np.array(img_after)
        diff = cv2.absdiff(cv_before, cv_after)
        _, thresh = cv2.threshold(diff, 30, 255, cv2.THRESH_BINARY)
        contours, _ = cv2.findContours(
            thresh, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE
        )
        for contour in contours:
            area = cv2.contourArea(contour)
            if area < self.MIN_CONTOUR_AREA:
                continue
            x, y, w, h = cv2.boundingRect(contour)
            if w == 0 or h == 0:
                continue
            aspect_ratio = float(w) / h if h > w else float(h) / w
            if aspect_ratio > self.MAX_ASPECT_RATIO:
                continue
            return True
        return False

    async def _listen_for_events(self):
        """The core loop that subscribes to Redis and dispatches events."""
        async with self._event_broker.pubsub() as pubsub:
            await pubsub.psubscribe(
                "app:comms:screen_frame",
                "app:comms:phone_utterance",
            )
            logger.info("Subscribed to event channels. Listening for events...")
            while not self._stop_event.is_set():
                try:
                    message = await pubsub.get_message(
                        ignore_subscribe_messages=True, timeout=1.0
                    )
                    if message:
                        channel = message["channel"]
                        event_data = json.loads(message["data"])
                        if channel == "app:comms:screen_frame":
                            if self._frame_queue.qsize() > (
                                self.FRAME_QUEUE_SIZE * self.ADAPTIVE_DROP_THRESHOLD
                            ):
                                logger.info(
                                    "Frame queue backlogged. Proactively dropping frame."
                                )
                                continue
                            try:
                                self._frame_sequence_id += 1
                                self._frame_queue.put_nowait(
                                    (self._frame_sequence_id, event_data)
                                )
                            except asyncio.QueueFull:
                                logger.warning(
                                    "Frame queue is full. Dropping incoming frame to maintain stability."
                                )
                        elif channel == "app:comms:phone_utterance":
                            self._trigger_turn_analysis(speech_event=event_data)
                    await self._flush_pending_events_on_timeout()
                except asyncio.TimeoutError:
                    continue
                except Exception as e:
                    logger.error(f"Error in event listener loop: {e}", exc_info=True)
                    await asyncio.sleep(1)

    async def _frame_processing_worker(self):
        """
        Pulls a frame from the queue, performs CPU-intensive analysis, and
        places the result onto the results queue for sequencing. This worker
        is stateless.
        """
        logger.info("Frame processing worker started.")
        loop = asyncio.get_running_loop()
        while not self._stop_event.is_set():
            try:
                seq_id, event_data = await self._frame_queue.get()
                frame_b64 = event_data["payload"]["frame_b64"]
                current_img_pil = await loop.run_in_executor(
                    self._cpu_executor, self._b64_to_image, frame_b64
                )
                await self._results_queue.put((seq_id, event_data, current_img_pil))
                self._frame_queue.task_done()
            except asyncio.CancelledError:
                logger.info("Frame processing worker cancelled.")
                break
            except Exception as e:
                logger.error(f"Error in frame processing worker: {e}", exc_info=True)
        logger.info("Frame processing worker stopped.")

    async def _sequencer(self):
        """
        Processes analysis results in strict order to prevent race conditions.
        This is the only task that modifies `_last_significant_frame_b64` and
        `_pending_vision_events`.
        """
        logger.info("Sequencer task started.")
        next_seq_id = 1
        results_buffer: Dict[int, Any] = {}
        loop = asyncio.get_running_loop()

        while not self._stop_event.is_set():
            try:
                if next_seq_id in results_buffer:
                    seq_id, event_data, current_img_pil = results_buffer.pop(
                        next_seq_id
                    )
                else:
                    (
                        seq_id,
                        event_data,
                        current_img_pil,
                    ) = await self._results_queue.get()

                if seq_id != next_seq_id:
                    results_buffer[seq_id] = (seq_id, event_data, current_img_pil)
                    continue

                self._last_activity_time = asyncio.get_event_loop().time()
                timestamp = event_data["payload"]["timestamp"]
                frame_b64 = event_data["payload"]["frame_b64"]
                self._frame_buffer.append((timestamp, frame_b64))

                if self._last_significant_frame_b64 is None:
                    self._last_significant_frame_b64 = frame_b64
                    self._last_significant_frame_pil = current_img_pil
                else:
                    mse = self._calculate_mse(
                        current_img_pil, self._last_significant_frame_pil
                    )
                    if mse > self.MSE_THRESHOLD:
                        score = await loop.run_in_executor(
                            self._cpu_executor,
                            ssim,
                            np.array(self._last_significant_frame_pil),
                            np.array(current_img_pil),
                        )
                        if score < self.SSIM_THRESHOLD:
                            is_significant = await loop.run_in_executor(
                                self._cpu_executor,
                                self._is_semantically_significant,
                                self._last_significant_frame_pil,
                                current_img_pil,
                            )
                            if is_significant:
                                logger.info(
                                    f"Sequencer: Significant visual event detected at t={timestamp:.2f}s"
                                )
                                self._pending_vision_events.append(
                                    {
                                        "timestamp": timestamp,
                                        "before_frame_b64": self._last_significant_frame_b64,
                                        "after_frame_b64": frame_b64,
                                    }
                                )
                                self._last_significant_frame_b64 = frame_b64
                                self._last_significant_frame_pil = current_img_pil

                next_seq_id += 1
            except asyncio.CancelledError:
                logger.info("Sequencer task cancelled.")
                break
            except Exception as e:
                logger.error(f"Error in sequencer: {e}", exc_info=True)
                await asyncio.sleep(1)
        logger.info("Sequencer task stopped.")

    async def _logging_dispatcher(self):
        """
        Waits for jobs in the queue, acquires the semaphore, and spawns
        a one-shot worker task for each job.
        """
        logger.info("Logging dispatcher started.")
        while not self._stop_event.is_set():
            try:
                log_job = await self._logging_queue.get()
                await self._logging_semaphore.acquire()
                asyncio.create_task(self._logging_worker(log_job))
                self._logging_queue.task_done()
            except asyncio.CancelledError:
                logger.info("Logging dispatcher received cancellation request.")
                break
            except Exception as e:
                logger.error(f"Error in logging dispatcher: {e}", exc_info=True)
        logger.info("Logging dispatcher stopped.")

    async def _logging_worker(self, log_job: tuple):
        """
        Processes a single log job and releases the semaphore upon completion.
        """
        try:
            speech_event, key_events, frame_map = log_job
            await self._log_turn_to_transcript(speech_event, key_events, frame_map)
        except Exception as e:
            logger.error(f"Error in logging worker: {e}", exc_info=True)
        finally:
            self._logging_semaphore.release()

    def _trigger_summary_update(self):
        """Schedules the summary update task, ensuring only one is running or scheduled (debouncing)."""
        if self._summary_update_task and not self._summary_update_task.done():
            logger.debug("Summary update task already scheduled. Skipping.")
            return
        logger.info("Scheduling session summary update.")
        self._summary_update_task = asyncio.create_task(self._update_summary())

    async def _update_summary(self):
        """A serialized task that updates the session summary using the latest events."""
        await asyncio.sleep(3.0)
        async with self._summary_update_lock:
            events_to_summarize, current_summary = [], ""
            async with self._state_lock:
                if not self._unsummarized_events:
                    logger.debug("No new events to summarize.")
                    return
                events_to_summarize = list(self._unsummarized_events)
                self._unsummarized_events.clear()
                current_summary = self._session_summary
            logger.info(
                f"Updating summary with {len(events_to_summarize)} new event(s)."
            )
            try:
                prompt = build_summary_update_prompt(
                    current_summary, events_to_summarize
                )
                new_summary = await self._summary_client.generate(prompt)
                if new_summary and isinstance(new_summary, str):
                    async with self._state_lock:
                        self._session_summary = new_summary.strip()
                    logger.info("Session summary updated successfully.")
                    logger.debug(f"New Summary: {self._session_summary}")
                else:
                    logger.warning(
                        "Summary update LLM call did not return a valid string."
                    )
            except asyncio.CancelledError:
                logger.info("Summary update task cancelled.")
                async with self._state_lock:
                    self._unsummarized_events = (
                        events_to_summarize + self._unsummarized_events
                    )
                raise
            except Exception as e:
                logger.error(f"Error during summary update: {e}", exc_info=True)
                async with self._state_lock:
                    self._unsummarized_events = (
                        events_to_summarize + self._unsummarized_events
                    )

    def _trigger_turn_analysis(self, speech_event: Optional[dict]):
        """
        Schedules a debounced turn analysis, cancelling any previously scheduled one.
        """
        self._last_activity_time = asyncio.get_event_loop().time()
        if self._debounce_task and not self._debounce_task.done():
            self._debounce_task.cancel()
        logger.info(f"Debouncing turn analysis for {self.DEBOUNCE_DELAY_SEC}s...")
        self._debounce_task = asyncio.create_task(
            self._debounced_analysis_runner(speech_event)
        )

    async def _debounced_analysis_runner(self, speech_event: Optional[dict]):
        """Waits for the debounce delay then runs the analysis."""
        try:
            await asyncio.sleep(self.DEBOUNCE_DELAY_SEC)
            visual_events_for_turn, latest_frame_for_turn = [], None

            if self._pending_vision_events:
                visual_events_for_turn = list(self._pending_vision_events)
                self._pending_vision_events.clear()

            if speech_event and not visual_events_for_turn and self._frame_buffer:
                latest_frame_for_turn = self._frame_buffer[-1]

            if not speech_event and not visual_events_for_turn:
                return
            logger.info("Debounce window ended. Triggering turn analysis...")
            asyncio.create_task(
                self._analyze_turn(
                    speech_event, visual_events_for_turn, latest_frame_for_turn
                )
            )
        except asyncio.CancelledError:
            logger.info("Debounced analysis was cancelled by a newer event.")

    async def _flush_pending_events_on_timeout(self):
        """
        On inactivity, triggers a silent turn analysis, but only if no other
        analyses are in progress.
        """
        time_since_activity = asyncio.get_event_loop().time() - self._last_activity_time
        is_debouncing = self._debounce_task and not self._debounce_task.done()
        if (
            time_since_activity > self.INACTIVITY_TIMEOUT_SEC
            and self._analyses_in_flight == 0
            and not is_debouncing
            and self._pending_vision_events
        ):
            logger.info("Inactivity timeout reached. Flushing pending vision events.")
            self._trigger_turn_analysis(speech_event=None)

    async def _analyze_turn(
        self,
        speech_event: Optional[dict],
        visual_events: List[Dict],
        latest_frame: Optional[Tuple[float, str]] = None,
    ):
        """
        A stateless method that analyzes a turn and queues the result for logging.
        """
        async with self._state_lock:
            self._analyses_in_flight += 1
        try:
            response, frame_map = await self._get_llm_analysis(
                speech_event, visual_events, latest_frame
            )
            key_events = response.events if response else []
            if key_events:
                async with self._state_lock:
                    for event in key_events:
                        self._recent_key_events.append(event)
                        self._unsummarized_events.append(event)
                self._trigger_summary_update()
            if key_events or speech_event:
                log_job = (speech_event, key_events, frame_map)
                try:
                    self._logging_queue.put_nowait(log_job)
                except asyncio.QueueFull:
                    logger.error(
                        "Logging queue is full. Dropping latest analysis result."
                    )
            for event in key_events:
                await self._event_broker.publish(
                    "app:comms:screen_annotation",
                    json.dumps(
                        {
                            "event_name": "ScreenAnnotationEvent",
                            "payload": {"event_description": event.event_description},
                        }
                    ),
                )
        except Exception as e:
            logger.error(
                f"An unhandled exception occurred during turn analysis task: {e}",
                exc_info=True,
            )
            if speech_event:
                log_job = (speech_event, [], {})
                try:
                    self._logging_queue.put_nowait(log_job)
                except asyncio.QueueFull:
                    logger.error(
                        "Logging queue is full. Dropping error-fallback analysis result."
                    )
        finally:
            async with self._state_lock:
                self._analyses_in_flight -= 1

    async def _get_llm_analysis(
        self,
        speech_event: Optional[dict],
        visual_events: List[Dict],
        latest_frame: Optional[Tuple[float, str]] = None,
    ) -> Tuple[Optional[TurnAnalysisResponse], Dict[float, str]]:
        """Constructs the prompt and calls the LLM to get turn analysis."""
        async with self._state_lock:
            current_summary = self._session_summary
            recent_key_events_copy = self._recent_key_events.copy()
        system_prompt = build_turn_analysis_prompt(
            current_summary, recent_key_events_copy
        )
        user_content, timestamp_to_frame_map = [], {}
        if speech_event:
            payload = speech_event["payload"]
            user_content.append(
                {"type": "text", "text": f"User Speech: \"{payload['content']}\""}
            )
            if "start_time" in payload and "end_time" in payload:
                user_content.append(
                    {
                        "type": "text",
                        "text": f"Speech Timestamps: Start={payload['start_time']:.2f}s, End={payload['end_time']:.2f}s",
                    }
                )
        if visual_events:
            user_content.append({"type": "text", "text": "\n--- Key Visual Frames ---"})
            bursts: List[List[Dict]] = []
            if visual_events:
                current_burst = [visual_events[0]]
                for i in range(1, len(visual_events)):
                    if (
                        visual_events[i]["timestamp"]
                        - visual_events[i - 1]["timestamp"]
                    ) <= self.BURST_DETECTION_THRESHOLD_SEC:
                        current_burst.append(visual_events[i])
                    else:
                        bursts.append(current_burst)
                        current_burst = [visual_events[i]]
                bursts.append(current_burst)
            frame_counter = 0
            for burst in bursts:
                events_to_process = burst
                if len(burst) > self.VISUAL_EVENT_SAMPLING_THRESHOLD:
                    logger.info(
                        f"Detected a burst of {len(burst)} events. Sampling down to 3."
                    )
                    user_content.append(
                        {
                            "type": "text",
                            "text": "\nNOTE: The following frames are a sampled summary (first, middle, last) of a rapid sequence of screen changes.",
                        }
                    )
                    events_to_process = [burst[0], burst[len(burst) // 2], burst[-1]]
                for ve in events_to_process:
                    frame_counter += 1
                    timestamp_to_frame_map[ve["timestamp"]] = ve["after_frame_b64"]
                    user_content.extend(
                        [
                            {
                                "type": "text",
                                "text": f"\nVisual Change #{frame_counter} at t={ve['timestamp']:.2f}s:",
                            },
                            {"type": "text", "text": "BEFORE:"},
                            {
                                "type": "image_url",
                                "image_url": {"url": ve["before_frame_b64"]},
                            },
                            {"type": "text", "text": "AFTER:"},
                            {
                                "type": "image_url",
                                "image_url": {"url": ve["after_frame_b64"]},
                            },
                        ]
                    )
        elif latest_frame:
            ts, b64 = latest_frame
            timestamp_to_frame_map[ts] = b64
            user_content.append(
                {"type": "text", "text": "\n--- Current Screen View ---"}
            )
            user_content.extend(
                [
                    {
                        "type": "text",
                        "text": f"This is the screen view at t={ts:.2f}s, when the user was speaking:",
                    },
                    {"type": "image_url", "image_url": {"url": b64}},
                ]
            )
        if not user_content:
            return None, {}
        try:
            self._analysis_client.set_system_message(system_prompt)
            response = await self._analysis_client.generate(user_message=user_content)
            if isinstance(response, TurnAnalysisResponse):
                return response, timestamp_to_frame_map
            elif isinstance(response, str):
                logger.warning(
                    "LLM analysis returned raw string. Attempting manual parse."
                )
                try:
                    return (
                        TurnAnalysisResponse.model_validate_json(response),
                        timestamp_to_frame_map,
                    )
                except (json.JSONDecodeError, Exception) as e:
                    logger.error(
                        f"Failed to manually parse LLM string response: {e}",
                        exc_info=True,
                    )
                    return None, {}
            else:
                logger.error(
                    f"Unexpected response type from LLM analysis: {type(response)}"
                )
                return None, {}
        except Exception as e:
            logger.error(f"Error during LLM analysis: {e}", exc_info=True)
            return None, {}

    async def _log_turn_to_transcript(
        self,
        speech_event: Optional[dict],
        key_events: List[KeyEvent],
        frame_map: Dict[float, str],
    ):
        """
        Handles the slow I/O of logging a turn to the TranscriptManager.
        """
        if not speech_event:
            if key_events:
                visual_only_events = [
                    evt for evt in key_events if evt.triggering_phrase is None
                ]
                if visual_only_events:
                    logger.info(
                        f"Storing {len(visual_only_events)} silent visual event(s)."
                    )
                    valid_timestamps = {
                        evt.representative_timestamp for evt in visual_only_events
                    }
                    filtered_frame_map = {
                        ts: frame
                        for ts, frame in frame_map.items()
                        if ts in valid_timestamps
                    }
                    async with self._state_lock:
                        self._stored_silent_key_events.extend(visual_only_events)
                        self._stored_silent_frame_map.update(filtered_frame_map)
            return
        async with self._state_lock:
            all_events = sorted(
                self._stored_silent_key_events + key_events, key=lambda e: e.timestamp
            )
            self._stored_silent_key_events.clear()
            combined_frame_map = self._stored_silent_frame_map.copy()
            self._stored_silent_frame_map.clear()
        combined_frame_map.update(frame_map)
        speech_payload = speech_event["payload"]
        speech_start_time, speech_end_time = speech_payload.get(
            "start_time"
        ), speech_payload.get("end_time")
        images_to_add, event_to_image_map = [], {}
        for event in all_events:
            rep_ts = event.representative_timestamp
            screenshot_b64 = combined_frame_map.get(rep_ts)
            if not screenshot_b64 and combined_frame_map:
                closest_ts = min(
                    combined_frame_map.keys(), key=lambda ts: abs(ts - rep_ts)
                )
                if abs(closest_ts - rep_ts) < 1.0:
                    screenshot_b64 = combined_frame_map[closest_ts]
            if screenshot_b64:
                images_to_add.append(
                    {"data": screenshot_b64, "caption": event.event_description}
                )
                event_to_image_map[event.timestamp] = len(images_to_add) - 1
        logged_image_ids = []
        if images_to_add:
            for attempt in range(self.IMAGE_UPLOAD_MAX_RETRIES):
                try:
                    logged_image_ids = await asyncio.to_thread(
                        self._image_manager.add_images, images_to_add
                    )
                    break
                except Exception as e:
                    logger.warning(
                        f"Image upload failed on attempt {attempt + 1}/{self.IMAGE_UPLOAD_MAX_RETRIES}: {e}"
                    )
                    if attempt + 1 == self.IMAGE_UPLOAD_MAX_RETRIES:
                        logger.error("Image upload failed after all retries.")
                        break
                    await asyncio.sleep(
                        self.IMAGE_UPLOAD_INITIAL_BACKOFF * (2**attempt)
                        + random.uniform(0, 1)
                    )
        timestamp_to_image_id = {}
        for ts, index in event_to_image_map.items():
            if index < len(logged_image_ids):
                timestamp_to_image_id[ts] = logged_image_ids[index]
        images_dict, screen_share_dict, primary_speech_event_handled = {}, {}, False
        for event in all_events:
            image_id = timestamp_to_image_id.get(event.timestamp)
            (
                rep_ts,
                screenshot_b64,
            ) = event.representative_timestamp, combined_frame_map.get(
                event.representative_timestamp
            )
            if not screenshot_b64 and combined_frame_map:
                closest_ts = min(
                    combined_frame_map.keys(), key=lambda ts: abs(ts - rep_ts)
                )
                if abs(closest_ts - rep_ts) < 1.0:
                    screenshot_b64 = combined_frame_map[closest_ts]
            if not screenshot_b64:
                logger.warning(
                    f"Could not find screenshot for event at {event.timestamp}"
                )
                continue
            event_type = "speech" if event.triggering_phrase else "vision"
            ts_key = ""
            if (
                event.triggering_phrase
                and not primary_speech_event_handled
                and speech_start_time is not None
                and speech_end_time is not None
            ):
                ts_key = f"{speech_start_time:.2f}-{speech_end_time:.2f}"
                primary_speech_event_handled = True
            else:
                ts_key = f"{event.timestamp:.2f}-{event.timestamp:.2f}"
            screen_share_dict[ts_key] = ScreenShareAnnotation(
                caption=event.event_description, image=screenshot_b64, type=event_type
            )
            if event.triggering_phrase and image_id:
                try:
                    start_index = speech_payload["content"].find(
                        event.triggering_phrase
                    )
                    if start_index != -1:
                        images_dict[
                            f"[{start_index}:{start_index + len(event.triggering_phrase)}]"
                        ] = image_id
                    else:
                        logger.warning(
                            f"Triggering phrase '{event.triggering_phrase}' not found in content."
                        )
                except ValueError:
                    logger.warning(
                        f"Triggering phrase '{event.triggering_phrase}' not found in content."
                    )
        message_to_log = Message(
            medium=Medium.PHONE_CALL,
            sender_id=speech_payload["contact_details"]["contact_id"],
            receiver_ids=[0],
            timestamp=datetime.fromisoformat(speech_payload["timestamp"]),
            content=speech_payload["content"],
            screen_share=screen_share_dict,
            images=images_dict,
        )
        logged_messages = self._transcript_manager.log_messages([message_to_log])
        if logged_messages:
            self._last_user_utterance_message_id = logged_messages[0].message_id
            logger.info(
                f"Logged turn to transcript with message_id: {self._last_user_utterance_message_id}"
            )
