from __future__ import annotations
import threading
from typing import Optional

__all__ = [
    "get_broader_context",
    "reset",
    "set_broader_context",
]

# ---------------------------------------------------------------------------
# Internal state guarded by a re-entrant lock so that nested acquisitions
# (unlikely but possible) do not dead-lock.
# ---------------------------------------------------------------------------

_LOCK = threading.RLock()

# ---------------------------------------------------------------------------
# Cached *broader context* (assistant + user bios + recent activity)
# ---------------------------------------------------------------------------

_BROADER_CONTEXT: Optional[str] = None


def get_broader_context(
    contact_manager=None,
) -> str:  # noqa: D401 – accept shared ContactManager
    """Return biographical context (assistant & user) **plus** recent activity.

    1. Fetch assistant and user records from the Contacts table via a *lazy*
       ContactManager import so we do **not** introduce hard import cycles
       during interpreter start-up.
    2. Compose a Markdown snippet that first introduces the assistant, then
       the user, explains their relationship, and finally appends the cached
       rolling-activity summary (generated by :func:`get_broader_context`).
    3. The assembled text is kept in the module-level cache so subsequent
       calls are lock-free.  Callers MUST invoke :func:`set_broader_context`
       whenever they persist new contact bios or a fresh rolling snapshot so
       every part of the system sees the updated context immediately.
    """

    global _BROADER_CONTEXT  # noqa: PLW0603 – module-level mutation intended

    if _BROADER_CONTEXT is not None:
        return _BROADER_CONTEXT

    with _LOCK:
        if _BROADER_CONTEXT is not None:
            return _BROADER_CONTEXT

        # -------- lazy imports to avoid circular dependencies -------------
        from unity.manager_registry import (
            ManagerRegistry,
        )  # noqa: WPS433  – runtime import
        from unity.memory_manager.memory_manager import (
            MemoryManager,
        )  # noqa: WPS433  – runtime import
        from unity.common.accessible_spaces_block import (
            build_accessible_spaces_block,
        )  # noqa: WPS433  – runtime import
        from unity.session_details import SESSION_DETAILS  # noqa: WPS433

        # ------------------------------------------------------------------
        # 1.  Gather assistant & user bios (robust to missing data) ---------
        cm = (
            contact_manager
            if contact_manager is not None
            else ManagerRegistry.get_contact_manager()
        )
        contacts = cm.filter_contacts(
            filter=(
                f"(contact_id == {SESSION_DETAILS.self_contact_id}) "
                f"or (contact_id == {SESSION_DETAILS.boss_contact_id})"
            ),
            limit=2,
        ).get("contacts", [])
        contacts_by_id = {contact.contact_id: contact for contact in contacts}

        # assistant ------------------------------------------------
        assist = contacts_by_id[SESSION_DETAILS.self_contact_id]
        assert assist
        assistant_name = " ".join(
            p for p in [assist.first_name, assist.surname] if p
        ).strip()
        assistant_bio = assist.bio if assist.bio else ""
        assistant_job_title = (getattr(assist, "job_title", "") or "").strip()

        # user -----------------------------------------------------
        u = contacts_by_id[SESSION_DETAILS.boss_contact_id]
        user_name = " ".join(p for p in [u.first_name, u.surname] if p).strip()
        user_bio = u.bio if u.bio else ""

        # ------------------------------------------------------------------
        # 2.  Retrieve rolling activity (may be empty) ---------------------
        rolling_activity = MemoryManager.get_rolling_activity()

        # ------------------------------------------------------------------
        # 3.  Build Markdown snippet ---------------------------------------
        parts: list[str] = []

        parts.append(f"You are a personal assistant named {assistant_name}.")
        if assistant_job_title:
            parts.append(f"Your main role / specialization is: {assistant_job_title}.")
        parts.append(f"You work directly for {user_name}.")
        if assistant_bio:
            parts.append("\nA bit about yourself:")
            parts.append(assistant_bio)
        if user_bio:
            parts.append(f"\nA bit about {user_name}, who you assist:")
            parts.append(user_bio)

        parts.append("")
        parts.append(build_accessible_spaces_block(SESSION_DETAILS.space_summaries))

        if rolling_activity:
            parts.append(
                f"\nYour activity logs explain broadly what you've been working on and how you've been assisting {user_name}.",
            )
            parts.append(
                "Please pay attention to these logs; always consider this broader context when deciding which actions are most appropriate to take.",
            )
            parts.append(
                "Sometimes the broader context is not relevant, but sometimes it can assist in reading between the lines for the current user intent.",
            )
            parts.append("")
            parts.append("# Activity Logs")
            parts.append(rolling_activity)

        _BROADER_CONTEXT = "\n".join(parts).strip()
        return _BROADER_CONTEXT


def set_broader_context(value: str) -> None:  # noqa: D401 – imperative helper name
    """Atomically replace the cached broader-context snippet with *value*."""

    global _BROADER_CONTEXT  # noqa: PLW0603 – intentional global write
    with _LOCK:
        _BROADER_CONTEXT = value


def reset() -> None:
    """Clear the cached broader-context snippet."""

    global _BROADER_CONTEXT  # noqa: PLW0603 – intentional global write
    with _LOCK:
        _BROADER_CONTEXT = None
