from __future__ import annotations
import threading
from typing import Optional

__all__ = [
    "get_broader_context",
    "set_broader_context",
]

# ---------------------------------------------------------------------------
# Internal state guarded by a re-entrant lock so that nested acquisitions
# (unlikely but possible) do not dead-lock.
# ---------------------------------------------------------------------------

_LOCK = threading.RLock()

# ---------------------------------------------------------------------------
# Cached *broader context* (assistant + user bios + recent activity)
# ---------------------------------------------------------------------------

_BROADER_CONTEXT: Optional[str] = None


def get_broader_context(
    contact_manager=None,
) -> str:  # noqa: D401 – accept shared ContactManager
    """Return biographical context (assistant & user) **plus** recent activity.

    1. Fetch assistant (``contact_id == 0``) and user (``contact_id == 1``)
       records from the Contacts table via a *lazy* ContactManager import so
       we do **not** introduce hard import cycles during interpreter start-up.
    2. Compose a Markdown snippet that first introduces the assistant, then
       the user, explains their relationship, and finally appends the cached
       rolling-activity summary (generated by :func:`get_broader_context`).
    3. The assembled text is kept in the module-level cache so subsequent
       calls are lock-free.  Callers MUST invoke :func:`set_broader_context`
       whenever they persist new contact bios or a fresh rolling snapshot so
       every part of the system sees the updated context immediately.
    """

    global _BROADER_CONTEXT  # noqa: PLW0603 – module-level mutation intended

    if _BROADER_CONTEXT is not None:
        return _BROADER_CONTEXT

    with _LOCK:
        if _BROADER_CONTEXT is not None:
            return _BROADER_CONTEXT

        # -------- lazy imports to avoid circular dependencies -------------
        from unity.contact_manager.contact_manager import (
            ContactManager,
        )  # noqa: WPS433  – runtime import
        from unity.memory_manager.memory_manager import (
            MemoryManager,
        )  # noqa: WPS433  – runtime import

        # ------------------------------------------------------------------
        # 1.  Gather assistant & user bios (robust to missing data) ---------
        cm = contact_manager if contact_manager is not None else ContactManager()
        contacts = sorted(
            cm._filter_contacts(
                filter="(contact_id == 0) or (contact_id == 1)",
                limit=2,
            ),
            key=lambda x: x.contact_id,
        )

        # assistant ------------------------------------------------
        assist = contacts[0]
        assert assist
        assistant_name = " ".join(
            p for p in [assist.first_name, assist.surname] if p
        ).strip()
        assistant_bio = assist.bio if assist.bio else ""

        # user -----------------------------------------------------
        user = cm._filter_contacts(filter="contact_id == 1", limit=1)
        u = user[0]
        user_name = " ".join(p for p in [u.first_name, u.surname] if p).strip()
        user_bio = u.bio if u.bio else ""

        # ------------------------------------------------------------------
        # 2.  Retrieve rolling activity (may be empty) ---------------------
        rolling_activity = MemoryManager.get_rolling_activity()

        # ------------------------------------------------------------------
        # 3.  Build Markdown snippet ---------------------------------------
        parts: list[str] = []

        parts.append(f"You are a personal assistant named {assistant_name}.")
        parts.append(f"You work directly for {user_name}.")
        if assistant_bio:
            parts.append("\nA bit about yourself:")
            parts.append(assistant_bio)
        if user_bio:
            parts.append(f"\nA bit about {user_name}, who you assist:")
            parts.append(user_bio)

        if rolling_activity:
            parts.append(
                f"\nYour activity logs explain broadly what you've been working on and how you've been assisting {user_name}.",
            )
            parts.append(
                "Please pay attention to these logs; always consider this broader context when deciding which actions are most appropriate to take.",
            )
            parts.append(
                "Sometimes the broader context is not relevant, but sometimes it can assist in reading between the lines for the current user intent.",
            )
            parts.append("")
            parts.append("# Activity Logs")
            parts.append(rolling_activity)

        _BROADER_CONTEXT = "\n".join(parts).strip()
        return _BROADER_CONTEXT


def set_broader_context(value: str) -> None:  # noqa: D401 – imperative helper name
    """Atomically replace the cached broader-context snippet with *value*."""

    global _BROADER_CONTEXT  # noqa: PLW0603 – intentional global write
    with _LOCK:
        _BROADER_CONTEXT = value
