from __future__ import annotations
import threading
from typing import Optional

__all__ = [
    "get_broader_context",
    "set_broader_context",
]

# ---------------------------------------------------------------------------
# Internal state guarded by a re-entrant lock so that nested acquisitions
# (unlikely but possible) do not dead-lock.
# ---------------------------------------------------------------------------

_LOCK = threading.RLock()

# ---------------------------------------------------------------------------
# Cached *broader context* (assistant + user bios + recent activity)
# ---------------------------------------------------------------------------

_BROADER_CONTEXT: Optional[str] = None


def get_broader_context() -> str:  # noqa: D401 – imperative helper name
    """Return biographical context (assistant & user) **plus** recent activity.

    1. Fetch assistant (``contact_id == 0``) and user (``contact_id == 1``)
       records from the Contacts table via a *lazy* ContactManager import so
       we do **not** introduce hard import cycles during interpreter start-up.
    2. Compose a Markdown snippet that first introduces the assistant, then
       the user, explains their relationship, and finally appends the cached
       rolling-activity summary (generated by :func:`get_broader_context`).
    3. The assembled text is kept in the module-level cache so subsequent
       calls are lock-free.  Callers MUST invoke :func:`set_broader_context`
       whenever they persist new contact bios or a fresh rolling snapshot so
       every part of the system sees the updated context immediately.
    """

    global _BROADER_CONTEXT  # noqa: PLW0603 – module-level mutation intended

    if _BROADER_CONTEXT is not None:
        return _BROADER_CONTEXT

    with _LOCK:
        if _BROADER_CONTEXT is not None:
            return _BROADER_CONTEXT

        # -------- lazy imports to avoid circular dependencies -------------
        try:
            from unity.contact_manager.contact_manager import (
                ContactManager,
            )  # noqa: WPS433  – runtime import
        except Exception:  # pragma: no cover – defensive fallback
            ContactManager = None  # type: ignore[assignment]

        # ------------------------------------------------------------------
        # 1.  Gather assistant & user bios (robust to missing data) ---------
        assistant_name = "Unknown Assistant"
        assistant_bio = ""
        user_name = "Unknown User"
        user_bio = ""

        try:
            if ContactManager is not None:
                cm = ContactManager()

                # assistant ------------------------------------------------
                assist = cm._search_contacts(filter="contact_id == 0", limit=1)
                if assist:
                    a = assist[0]
                    assistant_name = (
                        " ".join(p for p in [a.first_name, a.surname] if p).strip()
                        or assistant_name
                    )
                    assistant_bio = a.bio or ""

                # user -----------------------------------------------------
                user = cm._search_contacts(filter="contact_id == 1", limit=1)
                if user:
                    u = user[0]
                    user_name = (
                        " ".join(p for p in [u.first_name, u.surname] if p).strip()
                        or user_name
                    )
                    user_bio = u.bio or ""
        except Exception:  # pragma: no cover – tolerate offline tests
            pass

        # ------------------------------------------------------------------
        # 2.  Retrieve recent activity (may be empty) -----------------------
        try:
            recent_activity = get_broader_context()
        except Exception:  # pragma: no cover – defensive
            recent_activity = ""

        # ------------------------------------------------------------------
        # 3.  Build Markdown snippet ---------------------------------------
        parts: list[str] = []

        parts.append("# Assistant")
        parts.append(f"**{assistant_name}**")
        if assistant_bio:
            parts.append(assistant_bio)

        parts.append("")
        parts.append("# User")
        parts.append(f"**{user_name}**")
        if user_bio:
            parts.append(user_bio)

        parts.append("")
        parts.append("# Relationship")
        parts.append(
            f"{assistant_name.split(' ')[0] if assistant_name else 'The assistant'} is assisting {user_name}.",
        )

        if recent_activity:
            parts.append("")
            parts.append("# Recent Activity")
            parts.append(recent_activity)

        _BROADER_CONTEXT = "\n".join(parts).strip()
        return _BROADER_CONTEXT


def set_broader_context(value: str) -> None:  # noqa: D401 – imperative helper name
    """Atomically replace the cached broader-context snippet with *value*."""

    global _BROADER_CONTEXT  # noqa: PLW0603 – intentional global write
    with _LOCK:
        _BROADER_CONTEXT = value
