"""Global builtin-guidance catalogue: stable ids and idempotent seeding.

The catalogue lives in the public-read builtins project (see
``unify.common.builtins``) owned by the platform admin account. It stores
exactly one platform-wide copy of every builtin guidance entry; every
tenant reads it by default and never writes to it.

Two sources feed the default seeding set:

* the committed snapshot ``builtins_guidance.json`` next to this module,
  generated by ``scripts.skill_migration.builtins_import`` from upstream
  Agent Skills repositories pinned in a lockfile manifest, and
* ``PLATFORM_GUIDANCE_ENTRIES`` below — platform-authored entries versioned
  directly in code (kept out of the snapshot so importer regeneration can
  never drop them).

Seeding is hash-guarded per entry: only changed or removed entries are
deleted and re-inserted, so repeated runs are cheap and idempotent.

Builtin rows carry stable hash-based ``guidance_id`` values (derived from
the namespaced title) so they never collide semantically with tenant
auto-counting ids, and ``is_builtin=True`` for unambiguous provenance.
"""

from __future__ import annotations

import hashlib
import json
import logging
from pathlib import Path
from typing import Dict, List, Optional

import unisdk
from unisdk.utils.http import RequestError

from ..common.builtins import (
    builtins_project,
    ensure_builtins_project,
    read_seed_hashes,
    write_seed_hashes,
)
from ..common.embed_utils import ensure_vector_column
from ..common.model_to_fields import model_to_fields
from .types.guidance import Guidance

logger = logging.getLogger(__name__)

BUILTINS_GUIDANCE_CONTEXT = "Guidance"
BUILTINS_GUIDANCE_META_CONTEXT = "Guidance/Meta"
_HASH_MAP_KEY = "guidance_hash_by_skill"

# The backend refuses to embed inputs above ~8000 estimated tokens (0.25 per
# UTF-8 byte, i.e. ~32KB). Imported skills with inlined scripts routinely
# exceed that, so the content embedding ranks on a truncated head of the
# entry — where the description and body intro carry the retrieval signal —
# while the stored ``content`` column keeps the full text.
CONTENT_EMBED_HEAD_CHARS = 24000

SNAPSHOT_PATH = Path(__file__).with_name("builtins_guidance.json")

# Platform-authored builtin guidance, seeded alongside the imported-skills
# snapshot. Versioned in code (not in the snapshot) so importer regeneration
# can never drop it; edits here reseed automatically via the same per-entry
# hash guard.
_PLATFORM_MAP_CONTENT = """\
How to answer deep questions about the Unify platform — what it can do, how a
feature works, why the system behaved a certain way, or whether something is
possible.

Two authoritative resources exist; consult them before concluding anything is
unknown or impossible.

1. Product documentation (always current)
   - Index: fetch https://docs.unify.ai/llms.txt for every page URL.
   - Append `.md` to any page URL for clean markdown.
   - Sections mirror the product: Communication, Workspace, Integrations,
     Tasks, Learning, Canvas, Your Computer, Their Computer, Teams, Hiring —
     each with a `Developers` sub-section covering internals.
   - Best for: "what can it do", "how do I use X", setup and behavior
     questions. The docs are written for users and track the live deployment.

2. Platform source code (ground truth, hosted runtime only)
   Read-only source trees on the `local` execution surface (grep/read via
   `execute_code`; not present on self-host installs):
   - The running runtime source (importable `unify` package, typically
     `/app`): the assistant brain — ConversationManager, CodeActActor, all
     state managers (contacts, knowledge, tasks, guidance, functions, files,
     secrets, web), gateway, primitives. This is the exact code currently
     executing, so it can never be stale.
   - `/opt/system-sources/orchestra`: backend REST API + Postgres — users,
     projects, contexts, logging, assistants, billing, API keys.
   - `/opt/system-sources/console`: the web Console — dashboards, assistant
     management, onboarding checklist, interfaces/tabs/tiles.
   - `/opt/system-sources/unify-deploy`: hosted communication stack (phone,
     SMS, email, WhatsApp adapters), deployment infra, self-host stack.
   - `/opt/system-sources/docs`: the documentation source (mdx) for offline
     grep when web fetch is unavailable.
   Related open-source dependencies also present in the image: `/unisdk`
   (Python SDK wrapping Orchestra) and `/unillm` (LLM abstraction layer).
   Best for: precise behavior — exact limits, edge cases, supported
   providers, wire formats, error semantics — and anything the docs omit.

Routing hints
- Capability/product questions -> docs first, source second.
- "Why did it behave like that" / precise internals -> source first.
- Tool docstrings and the Accessible shared teams block are the
  authoritative contracts for API signatures, parameters (including
  destination / data_scope), and team:<id> routing. When those already
  answer how to perform a write or tool call, do it — do not grep platform
  source first to rediscover or confirm the contract, and do not delay the
  write while searching the codebase for schema examples or expected call
  shapes.
- The user-facing platform name in the docs may differ from internal package
  names; the internal runtime is the `unify` Python package regardless.

Confidentiality (non-negotiable)
- The source trees are proprietary and for your understanding only. Never
  reproduce source files or verbatim code excerpts to the user, never copy
  anything from them into ~/Unity/Local, Outputs/, attachments, or any
  synced or user-visible location, and never access them from desktop
  execution surfaces. Answer in your own words at the level of behavior and
  capability.
"""

PLATFORM_GUIDANCE_ENTRIES: Dict[str, Dict[str, str]] = {
    "platform/system-map": {
        "title": "[platform] Answering questions about the Unify platform itself",
        "content": _PLATFORM_MAP_CONTENT,
    },
}


def default_guidance_entries() -> Dict[str, Dict[str, str]]:
    """The full default seeding set: imported skills + platform entries."""
    return {**load_snapshot(), **PLATFORM_GUIDANCE_ENTRIES}


def stable_guidance_id(title: str) -> int:
    """Derive the stable builtin guidance id from a namespaced title.

    First 4 bytes of SHA-256, masked to the signed int32 range so backend
    integer sorting never overflows (mirrors primitive function ids).
    """
    digest = hashlib.sha256(title.encode("utf-8")).digest()
    return int.from_bytes(digest[:4], "big") & 0x7FFFFFFF


def entry_hash(title: str, content: str) -> str:
    """Content hash guarding per-skill reseeding."""
    return hashlib.sha256(f"{title}\x00{content}".encode("utf-8")).hexdigest()[:16]


def load_snapshot(path: Optional[Path] = None) -> Dict[str, Dict[str, str]]:
    """Load the committed builtins guidance snapshot (skill key → entry).

    Returns an empty mapping when the snapshot has not been generated yet.
    """
    path = path or SNAPSHOT_PATH
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("skills", {})


def _ensure_catalog_storage(project: str) -> None:
    """Create the catalogue project and contexts (idempotent).

    The context is created without the per-assistant Guidance foreign keys
    (cross-project FKs do not exist); builtin entries have empty ``images``
    and ``function_ids``.
    """
    ensure_builtins_project(project)
    unisdk.create_context(
        BUILTINS_GUIDANCE_CONTEXT,
        description="Builtin procedural guidance imported from the Agent Skills ecosystem.",
        unique_keys={"guidance_id": "int"},
        project=project,
    )
    # Pre-create the model schema so federated reads (from_fields
    # projections) are well-defined even before the first rows land.
    unisdk.create_fields(
        model_to_fields(Guidance),
        context=BUILTINS_GUIDANCE_CONTEXT,
        project=project,
    )
    unisdk.create_context(
        BUILTINS_GUIDANCE_META_CONTEXT,
        description="Seeding state for the builtin guidance catalogue.",
        unique_keys={"meta_id": "int"},
        project=project,
    )


def _delete_rows_by_ids(project: str, guidance_ids: List[int]) -> None:
    if not guidance_ids:
        return
    ids_expr = ", ".join(str(gid) for gid in sorted(set(guidance_ids)))
    logs = unisdk.get_logs(
        project=project,
        context=BUILTINS_GUIDANCE_CONTEXT,
        filter=f"guidance_id in [{ids_expr}]",
        return_ids_only=True,
    )
    if logs:
        unisdk.delete_logs(
            project=project,
            context=BUILTINS_GUIDANCE_CONTEXT,
            logs=logs,
        )


def _guidance_diff(
    project: str,
    desired: Dict[str, Dict[str, object]],
) -> tuple[List[str], List[str], Dict[str, Dict[str, object]]]:
    """Read-only diff of the stored guidance hashes against *desired*.

    Returns ``(changed_keys, removed_keys, current)``. Reads only, so it runs
    for any principal that can read the public Builtins project. Raises when the
    catalogue storage is absent (fresh project).
    """
    current = read_seed_hashes(
        project,
        meta_context=BUILTINS_GUIDANCE_META_CONTEXT,
        key=_HASH_MAP_KEY,
    )
    changed = [
        skill_key
        for skill_key, state in desired.items()
        if (current.get(skill_key) or {}).get("hash") != state["hash"]
    ]
    removed = [skill_key for skill_key in current if skill_key not in desired]
    return changed, removed, current


def _insert_entries(project: str, entries: List[Dict[str, str]]) -> None:
    if not entries:
        return
    rows = [
        Guidance(
            guidance_id=stable_guidance_id(entry["title"]),
            title=entry["title"],
            content=entry["content"],
            is_builtin=True,
        ).model_dump(mode="json")
        for entry in entries
    ]
    unisdk.create_logs(
        project=project,
        context=BUILTINS_GUIDANCE_CONTEXT,
        entries=rows,
        recompute_derived=True,
    )


def seed_builtin_guidance(
    *,
    project: Optional[str] = None,
    entries: Optional[Dict[str, Dict[str, str]]] = None,
) -> bool:
    """Seed the global builtins guidance catalogue from the snapshot.

    Idempotent and hash-guarded per skill: only skills whose title/content
    changed (or disappeared from the snapshot) are deleted and re-inserted,
    with ``recompute_derived=True`` so embeddings recompute only for written
    rows. Always ensures the ``content`` and ``title`` vector columns exist
    when the catalogue has rows, so read-only consumers can run ranked
    semantic search without any write access.

    Returns True when any rows were written or removed, False when already
    up to date.
    """
    project = project or builtins_project()
    entries = entries if entries is not None else default_guidance_entries()
    desired = {
        skill_key: {
            "hash": entry_hash(entry["title"], entry["content"]),
            "guidance_id": stable_guidance_id(entry["title"]),
        }
        for skill_key, entry in entries.items()
    }

    logger.info(
        "Starting builtins guidance catalogue seed project=%s skills=%d",
        project,
        len(entries),
    )

    # Read-only convergence probe (see seed_builtin_primitives): public-read
    # Builtins lets any principal verify convergence; an already-seeded
    # catalogue is a no-op. A missing catalogue raises and falls through to the
    # owner seed path.
    try:
        changed_keys, removed_keys, current = _guidance_diff(project, desired)
        storage_ready = True
    except RequestError:
        storage_ready = False

    if storage_ready and not changed_keys and not removed_keys:
        logger.info(
            "Builtins guidance catalogue already converged project=%s skills=%d; "
            "read-only no-op",
            project,
            len(entries),
        )
        return False

    _ensure_catalog_storage(project)
    if not storage_ready:
        changed_keys, removed_keys, current = _guidance_diff(project, desired)

    if changed_keys or removed_keys:
        stale_ids = [
            (current.get(skill_key) or {}).get("guidance_id")
            for skill_key in changed_keys + removed_keys
        ]
        stale_ids = [gid for gid in stale_ids if gid is not None]
        stale_ids.extend(
            desired[skill_key]["guidance_id"] for skill_key in changed_keys
        )
        _delete_rows_by_ids(project, stale_ids)
        _insert_entries(project, [entries[skill_key] for skill_key in changed_keys])
        write_seed_hashes(
            project,
            desired,
            meta_context=BUILTINS_GUIDANCE_META_CONTEXT,
            key=_HASH_MAP_KEY,
        )
        logger.info(
            "Seeded builtins guidance project=%s changed=%d removed=%d",
            project,
            len(changed_keys),
            len(removed_keys),
        )
    else:
        logger.info(
            "Builtins guidance catalogue already up to date project=%s skills=%d; "
            "skipping row rewrites",
            project,
            len(entries),
        )

    if desired:
        logger.info("Ensuring builtins guidance embedding columns project=%s", project)
        ensure_vector_column(
            BUILTINS_GUIDANCE_CONTEXT,
            embed_column="_content_emb",
            source_column="_content_head",
            derived_expr=f"str({{content}})[:{CONTENT_EMBED_HEAD_CHARS}]",
            project=project,
        )
        ensure_vector_column(
            BUILTINS_GUIDANCE_CONTEXT,
            embed_column="_title_emb",
            source_column="title",
            project=project,
        )
    return bool(changed_keys or removed_keys)


__all__ = [
    "BUILTINS_GUIDANCE_CONTEXT",
    "BUILTINS_GUIDANCE_META_CONTEXT",
    "PLATFORM_GUIDANCE_ENTRIES",
    "SNAPSHOT_PATH",
    "default_guidance_entries",
    "entry_hash",
    "load_snapshot",
    "seed_builtin_guidance",
    "stable_guidance_id",
]
