"""Global builtin-guidance catalogue: stable ids and idempotent seeding.

The catalogue lives in the public-read builtins project (see
``unify.common.builtins``) owned by the platform admin account. It stores
exactly one platform-wide copy of every builtin guidance entry; every
tenant reads it by default and never writes to it.

Two sources feed the default seeding set:

* the committed snapshot ``builtins_guidance.json`` next to this module,
  generated by ``scripts.skill_migration.builtins_import`` from upstream
  Agent Skills repositories pinned in a lockfile manifest, and
* ``PLATFORM_GUIDANCE_ENTRIES`` below — platform-authored entries versioned
  directly in code (kept out of the snapshot so importer regeneration can
  never drop them).

Seeding is hash-guarded per entry: only changed or removed entries are
deleted and re-inserted, so repeated runs are cheap and idempotent.

Builtin rows carry stable hash-based ``guidance_id`` values (derived from
the namespaced title) so they never collide semantically with tenant
auto-counting ids, and ``is_builtin=True`` for unambiguous provenance.
"""

from __future__ import annotations

import hashlib
import json
import logging
from pathlib import Path
from typing import Dict, List, Optional

import unisdk
from unisdk.utils.http import RequestError

from ..common.builtins import (
    builtins_project,
    ensure_builtins_project,
    read_seed_hashes,
    write_seed_hashes,
)
from ..common.embed_utils import ensure_vector_column
from ..common.model_to_fields import model_to_fields
from .types.guidance import Guidance

logger = logging.getLogger(__name__)

BUILTINS_GUIDANCE_CONTEXT = "Guidance"
BUILTINS_GUIDANCE_META_CONTEXT = "Guidance/Meta"
_HASH_MAP_KEY = "guidance_hash_by_skill"

# The backend refuses to embed inputs above ~8000 estimated tokens (0.25 per
# UTF-8 byte, i.e. ~32KB). Imported skills with inlined scripts routinely
# exceed that, so the content embedding ranks on a truncated head of the
# entry — where the description and body intro carry the retrieval signal —
# while the stored ``content`` column keeps the full text.
CONTENT_EMBED_HEAD_CHARS = 24000

SNAPSHOT_PATH = Path(__file__).with_name("builtins_guidance.json")

# Platform-authored builtin guidance, seeded alongside the imported-skills
# snapshot. Versioned in code (not in the snapshot) so importer regeneration
# can never drop it; edits here reseed automatically via the same per-entry
# hash guard.
_PLATFORM_MAP_CONTENT = """\
How to answer deep questions about the Unify platform — what it can do, how a
feature works, why the system behaved a certain way, or whether something is
possible.

Two authoritative resources exist; consult them before concluding anything is
unknown or impossible. The source trees are proprietary — never reproduce
file contents or verbatim code to the user (full confidentiality rules
below); answer in your own words.

1. Product documentation (always current)
   - Index: fetch https://docs.unify.ai/llms.txt for every page URL.
   - Append `.md` to any page URL for clean markdown; retrieve pages with
     `primitives.web`.
   - Sections mirror the product: Communication, Workspace, Integrations,
     Tasks, Learning, Canvas, Twin's Computer, Your Computer, Teams, Hiring —
     each with a `Developers` sub-section covering internals.
   - Best for: "what can it do", "how do I use X", setup and behavior
     questions. The docs are written for users and track the live deployment.

2. Platform source code (ground truth, hosted runtime only)
   Read-only source trees on the `local` execution surface (grep/read via
   `execute_code`; not present on self-host installs):
   - The running runtime source (importable `unify` package, typically
     `/app`): the assistant brain — ConversationManager, CodeActActor, all
     state managers (contacts, knowledge, tasks, guidance, functions, files,
     secrets, web), gateway, primitives. This is the exact code currently
     executing, so it can never be stale.
   - `/opt/system-sources/orchestra`: backend REST API + Postgres — users,
     projects, contexts, logging, assistants, billing, API keys.
   - `/opt/system-sources/console`: the web Console — canvases, assistant
     management, onboarding checklist, interfaces/tabs/tiles.
   - `/opt/system-sources/unify-deploy`: hosted communication stack (phone,
     SMS, email, WhatsApp adapters), deployment infra, self-host stack.
   - `/opt/system-sources/docs`: the documentation source (mdx) for offline
     grep when web fetch is unavailable.
   Related open-source dependencies also present in the image: `/unisdk`
   (Python SDK wrapping Orchestra) and `/unillm` (LLM abstraction layer).
   Best for: precise behavior — exact limits, edge cases, supported
   providers, wire formats, error semantics — and anything the docs omit.

Routing hints
- Capability/product questions -> docs first, source second.
- "Why did it behave like that" / precise internals -> source first.
- Tool docstrings and the Accessible shared teams block are the
  authoritative contracts for API signatures, parameters (including
  destination / data_scope), and team:<id> routing. When those already
  answer how to perform a write or tool call, do it — do not grep platform
  source first to rediscover, confirm, or second-guess the contract, and do
  not delay or refuse the write while searching the codebase for schema
  examples, "expected" call shapes, or a pre-existing object token when the
  docs say to create under the chosen destination.
- The user-facing platform name in the docs may differ from internal package
  names; the internal runtime is the `unify` Python package regardless.

Confidentiality (non-negotiable)
- The source trees are proprietary and for your understanding only. Never
  reproduce source files or verbatim code excerpts to the user, never copy
  anything from them into ~/Unity/Local, Outputs/, attachments, or any
  synced or user-visible location, and never access them from desktop
  execution surfaces. Answer in your own words at the level of behavior and
  capability — summaries, explanations, and "yes/no with caveats" are always
  fine; file contents are not.
"""

_MACOS_UNLOCK_CONTENT = """\
How to recognise and unlock a locked macOS user desktop (screensaver or lock
screen) on a linked user machine.

A linked Mac that has been left alone is locked, and the live capture then
shows its screensaver, not a desktop. You know a linked machine is a Mac from
`primitives.computer.user_desktop.list_linked()[...].os == 'macos'` — that
field is authoritative; never identify the OS from a screenshot or an LLM's
guess.

Recognise the locked state
- A full-screen moving/abstract pattern with no menu bar, no Dock, and no
  window chrome is the screensaver: the machine is locked or idle. It is not
  artwork, a wallpaper, a browser, or an app the user opened.
- The explicit lock screen (a centred clock + date, a user avatar, and an
  `Enter Password` / `Touch ID or Enter Password` field) is also the locked
  state.
- In either case treat the Mac as locked — do not describe the pattern as
  on-screen content, and do not ask the user what "unlock" means; recognising
  and clearing the lock is your job.

Unlock with the saved password (low-level, deterministic)
- The user's login password is stored as the secret
  `MACOS_USER_DESKTOP_PASSWORD`. Use the placeholder form
  `${MACOS_USER_DESKTOP_PASSWORD}` — it is resolved to the real value on
  their machine at the call boundary, so the plaintext never enters your
  context.
- Judge each screen with `query_llm(prompt, images=[png_bytes])` — pass the
  screenshot to the LLM to decide what state the Mac is in. Drive the actions
  with the low-level session methods (`press_key`, `get_screenshot`,
  `type_text`, `press_enter`), never `act()`/`observe()`, and read every
  screenshot back through `query_llm(images=...)`:

    import io
    ud = primitives.computer.user_desktop.session()
    def _png(img):
        buf = io.BytesIO(); img.save(buf, 'PNG'); return buf.getvalue()
    shot = _png(await ud.get_screenshot())
    state = await query_llm(
        'Is this a macOS lock screen or screensaver (a clock/avatar, a '
        'password field, or a full-screen moving pattern)? Answer locked '
        'or unlocked.', images=[shot])
    # If locked / screensaver:
    await ud.press_key('esc')                    # wake the display
    shot = _png(await ud.get_screenshot())
    ready = await query_llm('Is a focused macOS password field visible '
        'and ready for input? Answer yes or no.', images=[shot])
    # Only once the field is confirmed present and focused:
    await ud.type_text('${MACOS_USER_DESKTOP_PASSWORD}')  # placeholder; resolved on-device
    await ud.press_enter()
    shot = _png(await ud.get_screenshot())
    done = await query_llm('Is this an unlocked desktop now (no lock '
        'screen)? Answer yes or no, then briefly describe it.', images=[shot])

- Confirm before you type: only `type_text` the password after a
  `query_llm(images=...)` check confirms the macOS password field is on
  screen and focused. Never type it blind into a screensaver or a focused
  app — that could mis-send the secret or surface it on screen.
- Never read, print, log, or echo the password value, and never ask the user
  to paste their password into chat — only ever reference
  `${MACOS_USER_DESKTOP_PASSWORD}`. If the placeholder stays literal or the
  field never accepts it, the secret is probably unset: tell the user to
  save it in the Console ('Save User Password').

Reporting
- If asked what's on the screen while it's the screensaver, say the Mac is
  locked and offer to unlock it (or just unlock it if they already asked you
  to look) — do not describe the screensaver pattern as content.
- Fail honestly: if waking never reveals a login field, or the password is
  not accepted, report that the Mac is locked and you could not drive the
  login screen, and ask them to unlock it locally. Do not retry endlessly or
  invent a description of a screen you cannot see.
"""

_USER_DESKTOP_FILES_CONTENT = """\
How to read, fetch, or sync a linked user's desktop files ("sync my
filesystem", "pull my desktop files", "back up my home folder", "what's in
my Documents?").

`primitives.computer.user_desktop.files` is the canonical path. It
reads/writes the user's home over SFTP and mirrors what you pull into
`~/Unity/Remote/<user_id>/`, returning local paths you can parse. It is a
separate capability from the screen-control session — reach for it whenever
the task is about file content rather than driving their screen.

The model is mounting-like: browse cheaply, then fetch only what you need.
- `files.list(path='', user_id=...)` — browse their home tree with no copy
  ('' lists the home root; directories carry a trailing '/'). Start here; it
  shows the full tree.
- `files.pull(path, user_id=...)` — stage one home-relative file into the
  mirror when you need its contents or want to edit it; returns its absolute
  local path. This is your default fetch. Copies skip noise (caches, deps,
  VCS metadata) and credential dirs (`.ssh`/`.gnupg`/`.aws`/…), so they're
  never exfiltrated.
- `files.sync(path='', user_id=...)` — bulk-mirror a whole subtree at once.
  Use only when you genuinely need everything under it; scope to a subtree
  (e.g. 'Documents') since '' (entire home) is heavy and slow. Prefer
  `list`+`pull` otherwise.
- `files.push(local_path, dest_path, user_id=...)` — write a file back
  (saved as a timestamped copy; never overwrites their original).

Example (read lazily, NOT via shell — browse, then pull):

    names = await primitives.computer.user_desktop.files.list('Documents')
    path = await primitives.computer.user_desktop.files.pull('Documents/report.pdf')
    display(await primitives.files.parse(path))  # work from the staged mirror

Such requests are first-class file requests — not ambiguous "sync to where?"
questions. Default to `files.list` then `files.pull` for the specific paths
in play; reserve `files.sync` for an explicit request to copy an entire
folder. The destination is always your local mirror, so never ask the user
where to sync to. Never harvest their files by running shell
`find`/`cat`/`tar`/`base64`/`cp`/`scp`/`rclone` on
`surface="user_desktop"` — that surface is only for commands the user
explicitly wants executed on their machine, not for retrieving file content.
"""

_INTEGRATIONS_ENVELOPES_CONTENT = """\
How to integrate with external services and connected apps (cloud storage,
CRMs, Slack, project tools, accounting software, Google/Microsoft workspace):
credentials, the workspace OAuth proxy, result envelopes, and scope checks.

Operative contract
- Credentials first: check `primitives.secrets.ask(...)` for stored API
  credentials/tokens. If absent, tell the caller to connect the app from
  the Console **Integrations** tab (plug icon). Static keys sync to the
  SecretManager `.env`; read them with `os.environ` after confirming their
  names.
- Connected-account (BYOD) OAuth calls go through the LOCAL WORKSPACE PROXY,
  never the real provider hosts. `get_oauth_access_token(provider)` returns
  a proxy capability handle (NOT a real token) for the
  `Authorization: Bearer ...` header, and the base URL must be the proxy:
  `os.environ["MICROSOFT_GRAPH_BASE"]` (~ graph.microsoft.com/v1.0),
  `os.environ["GOOGLE_DRIVE_BASE"]` (~ googleapis.com/drive/v3), or
  `GOOGLE_API_BASE` for other Google services. Calls straight to
  `graph.microsoft.com` / `www.googleapis.com` carry no valid token and
  fail — the sandbox holds no real provider token by design.
- No custom retry/sleep loops around provider tool calls — Orchestra/Unify
  already retry transient failures inside `primitives.integrations.*` /
  `execute_tool`. Call once; handle the FINAL ENVELOPE: `ok`,
  `connect_required`, `confirmation_required`, `missing_scope`,
  `provider_error`, …. Long domain waits (e.g. a GitHub rate-limit window
  during a bulk crawl) are the only exception.
- The user's connected Gmail/Outlook mailbox is first-class: use
  `primitives.workspace_email.*`, never hand-rolled Gmail/Graph mail calls —
  that sends AS THE USER; `primitives.comms.send_email` sends AS THE
  ASSISTANT from its own managed mailbox (contact-graph aware).
- Scope check: a required raw OAuth scope absent from a present
  `GOOGLE_GRANTED_SCOPES` / `MICROSOFT_GRANTED_SCOPES` secret means DO NOT
  attempt the call (procedure below); secret missing entirely → proceed
  normally.

Full integration pattern
1. Check for credentials (`primitives.secrets.ask`) as above.
2. Install the SDK: `install_python_packages` with the service's official
   Python SDK (e.g. `google-cloud-storage`, `slack-sdk`, `boto3`, `stripe`).
   Prefer Python SDKs over CLI tools: packages get isolated venvs and
   dependency resolution; shell CLIs have no equivalent management.
3. Integrate: for provider SDKs that read OAuth credentials from environment
   variables, prefer the SDK's default credential behavior. For explicit
   connected-account REST, use the proxy:

       import os, httpx
       token = get_oauth_access_token("microsoft")
       base = os.environ["MICROSOFT_GRAPH_BASE"]
       resp = httpx.get(
           f"{base}/me/drive/root/children",
           headers={"Authorization": f"Bearer {token}"},
       )

   Provider SDKs work too — point the client's base/endpoint at the proxy
   (msgraph's `request_adapter.base_url`, googleapiclient's
   `client_options.api_endpoint`). The proxy exposes the FULL provider REST
   surface (list, search, read, rename, move, upload, delete, `$batch`, …)
   but enforces the per-assistant file-access allowlist: files and folders
   the user has not permitted are masked — absent from listings/search,
   not-found on direct access, and writes into non-permitted locations are
   rejected. Treat masked items as nonexistent.
4. Store for reuse: after a successful integration, store reusable functions
   via `store_skills` and document the setup via `GuidanceManager_add_guidance`.
   Reusable OAuth integrations call `get_oauth_access_token(provider)` at
   runtime; never store or capture a concrete access-token value inside a
   function implementation.

Checking OAuth scope before API calls
- `GOOGLE_GRANTED_SCOPES` and `MICROSOFT_GRANTED_SCOPES` hold space-separated
  raw OAuth scope strings — not feature names. Google scopes are full URLs
  (`https://www.googleapis.com/auth/drive`,
  `https://www.googleapis.com/auth/gmail.send`). Microsoft scopes are Graph
  URLs (`https://graph.microsoft.com/Sites.Read.All`) plus the bare
  `offline_access`.
- Procedure: look up the scope(s) the specific API call requires from the
  provider's official docs or SDK at call time, then check membership against
  the granted-scopes secret. There is no per-feature catalog — do not rely on
  one.
- Microsoft normalization: provider docs list short names (`Sites.Read.All`);
  the secret stores them URL-prefixed. Prefix the short name with
  `https://graph.microsoft.com/` before searching (only `offline_access` is
  stored bare). Example: SharePoint reads need `Sites.Read.All`, so search
  `MICROSOFT_GRANTED_SCOPES` for
  `https://graph.microsoft.com/Sites.Read.All` (or `.../Sites.ReadWrite.All`
  for writes).
- Decision rules: secret missing entirely → proceed normally (expected for
  Microsoft enterprise admin-consented tenants and self-managed BYO tokens).
  Secret present + required scope present → proceed. Secret present +
  required scope absent → do not attempt the call; tell the user that access
  is not currently enabled and they can add it by reconnecting the service
  from the Console **Integrations** tab.

Result envelopes in depth
- `primitives.integrations.*` / `execute_tool` calls return the provider
  execution envelope built by Orchestra. Treat every non-ok status as an
  actionable outcome to explain to the user, not an exception to retry:
  `connect_required` (no active connection — ask the user to connect the
  app in Console Integrations), `confirmation_required` (see below),
  `missing_scope`, `expired`, `blocked_by_policy`, `provider_error` /
  `error`.
- `confirmation_required` surfaces as a pending-approval payload
  (`type: integration_tool_pending_approval`, `status: pending_approval`)
  whose `approval` block carries `audit_id`, `connection_id`, `tool_id`,
  the app/tool display names, `action_class`, `arguments_summary`,
  `approval_options`, a `confirmation_token`, and `expires_at`. Sensitive,
  write, destructive, and bulk-export actions go through this approved
  confirmation flow — relay it to the user; never bypass it or blindly
  re-fire the call.
- Connection/status discovery: `primitives.integrations.search_integrations`
  rows carry `deployment_status`, `connection_status`, `sync_status`, and a
  ready-made `next_action` sentence — follow it. `sync_status ==
  "tools_not_connected"` means provider-event triggers are available via
  the existing workspace connection, but executing this app's tools needs a
  Composio/Pipedream account added in Console Integrations.

Credential flows in depth
Three distinct credential classes, with different storage and visibility:
1. Static keys/tokens (API keys the user pasted in Console Integrations):
   synced from Orchestra by the SecretManager into the `Secrets` context,
   `.env`, and `os.environ`. Readable directly after confirming names via
   `primitives.secrets.ask(...)`.
2. Connected-account OAuth tokens (raw access/refresh tokens): NEVER
   mirrored into the `Secrets` context, `.env`, or `os.environ`. They live
   only in the SecretManager's in-memory OAuth store and are used by the
   trusted runtime (the localhost provider proxy and first-party managers
   such as workspace email). Sandboxed code cannot read them by design.
3. The sandbox-facing capability: `get_oauth_access_token(provider)`
   returns the workspace proxy nonce — see below.
Token freshness is the proxy's job, per upstream call: on a provider 401
it forces a secret re-sync from Orchestra and retries once (the platform
refresh job persists new tokens to Orchestra on a ~30-minute cadence); if
the token is still stale it surfaces a clean "reconnect account" 401 —
relay that to the user instead of retrying.

Proxy-nonce contract in depth
- The value returned by `get_oauth_access_token(provider)` is a local
  capability handle scoped to this workspace's proxy — it is worthless
  outside the sandbox and against real provider hosts. Never print, log,
  return, or store it; stored/reusable functions must call
  `get_oauth_access_token(provider)` at runtime on every run.
- Provider aliases are accepted: `microsoft` / `msft` / `ms365` /
  `microsoft_365` / `graph`, and `google` / `gmail` / `google_workspace` /
  `drive`. Multiple providers can be used in one sandbox — request each
  explicitly.
- The proxy base URLs and nonce are overlaid into venv and persistent
  shell/subprocess sandboxes on each execution, so long-lived sessions
  keep working across proxy restarts — read the base from `os.environ`
  at call time rather than caching it.
"""

_MANAGER_ROUTING_CONTENT = """\
Which state manager to use when two overlap: `primitives.data` vs
`primitives.files`, data vs `primitives.ingestion` (reading vs storing), and
`primitives.workspace_email` vs `primitives.comms` email.

CRITICAL: `primitives.data.*` vs `primitives.files.*` — these serve
DIFFERENT purposes, do not confuse them:
- `primitives.data.*`: ALL analytical and data operations — filtering,
  searching, aggregating, joining. Works on any Unify context (`Data/*`,
  `Files/*`, `Knowledge/*`). Use when the question is about DATA INSIDE
  tables, regardless of where those tables came from. Always prefer
  server-side `filter=` / `reduce` / join variants over fetching rows into
  Python loops.
- `primitives.files.*`: file-specific operations — describing the storage
  layout of an uploaded/received file, listing files in the file registry,
  parsing documents, rendering PDFs/Excel sheets as images for visual
  inspection. Use when the question is about FILES themselves (metadata,
  layout, parsing) or when you need file-path-based context resolution.
  (Worked examples at the end.)

Reading vs storing: `primitives.data.*` vs `primitives.ingestion.*`
- `data` reads and reshapes what is already stored (filter, search, reduce,
  join, update_rows). STORING new data is not data's job: anything that puts
  NEW data somewhere queryable — API responses, connected-app pulls, files,
  folders, table reshapes — goes through `primitives.ingestion.submit`.
- If an ingestion run fails, read `get_logs(run_id)`, fix the cause, and
  submit again. Do not store the data another way (`create_table` +
  `insert_rows`, hand-written loops): those write rows nothing checkpoints,
  verifies against a declared count, or can resume, so a part-way failure
  leaves a table that looks complete. Report the limitation instead.

Email: `primitives.workspace_email.*` vs `primitives.comms.send_email`
- `workspace_email` sends AS THE USER from their own CONNECTED Google
  Workspace / Microsoft 365 mailbox (the OAuth-linked account);
  `comms.send_email` sends AS THE ASSISTANT from its managed mailbox and is
  wired into the contact graph.
- Choose `comms.send_email` for assistant-owned outreach;
  `workspace_email.send` only when the message must originate from the
  user's connected account. `workspace_email` recipients are plain
  email-address strings, not contact ids; it requires a connected workspace
  account and errors clearly if none is connected.

Manager selection priorities (when in doubt, the most specific domain wins):
1. `transcripts` for historical communications (what was said/written)
2. `contacts` for people/relationship information
3. `tasks` for work items, deadlines, assignments
4. `web` for current external information (weather, news, real-time data)
5. `files` when dealing with specific documents or file-level operations
6. `data` for tabular Orchestra contexts (`Data/*` and other tables):
   filter, reduce, join, update_rows — never client-scan large tables in
   Python

Typed claim / procedure catalogues (`KnowledgeManager_*`,
`GuidanceManager_*`) are top-level Actor JSON tools, not `primitives.*` —
use them for durable domain claims and SOPs.

Worked examples (data vs files):
- "What tables exist under Data/examplehousing?" ->
  `primitives.data.list_tables(prefix=...)` (data)
- "Describe the schema of the repairs table" ->
  `primitives.data.describe_table(...)` (data)
- "What's in the uploaded PDF?" ->
  `primitives.files.describe(file_path=...)` (files)
- "Render page 3 of the report as an image" ->
  `primitives.files.render_pdf(...)` (files)
"""

_DESKTOP_PROCEDURES_CONTENT = """\
Whose desktop to drive and how to read a screen: your managed desktop vs a
user's linked desktop (rules of engagement), screenshots for the user vs the
LLM, and coordinate spaces.

Operative contract
- `primitives.computer.desktop` and `primitives.computer.web` always drive
  YOUR OWN managed desktop (the machine in the Console live view) — the
  default workspace for every task. `primitives.computer.user_desktop`
  drives a user's own physical machine linked in the Console; it is never in
  the live view and is their personal computer.
- user_desktop rules of engagement: (1) only on explicit request — the user
  clearly asked for something on THEIR computer; (2) clarify when unsure
  which machine/target is meant rather than guessing; (3) confirm before
  consequential actions (destructive, irreversible, sends/deletes/purchases
  on their behalf); (4) a `PermissionError` means control was revoked —
  stop immediately, do not retry, continue only on your own desktop;
  (5) NEVER modify their machine to work around an error (no installing
  software, package managers, or patch files — report the failure and stop);
  (6) discover machines with `primitives.computer.user_desktop.list_linked()`
  and select with `session(user_id=...)`.
- Viewing state: `get_screenshot()` returns a PIL Image; `display()` renders
  it for the USER to see. To INTERPRET a screen yourself, send it to the LLM
  with `query_llm(prompt, images=[...])` — do not call `observe()`/`act()`
  just to get a description, and do not relay a weaker side model's caption.
  Take the OS from `user_desktop.list_linked()[...].os`, never from pixels.
- Coordinate spaces are NOT interchangeable: desktop and visible-web share
  the full-display space; headless (`visible=False`) screenshots are
  viewport-only. Read `click(x, y)` coordinates from the SAME session's
  `get_screenshot()` — mixing spaces causes systematic misclicks.
- Their files: use `primitives.computer.user_desktop.files`
  (`list`/`pull`/`push`, bulk `sync`), never shell
  `find`/`cat`/`tar`/`base64`/`cp`/`scp`/`rclone` on
  `surface="user_desktop"` — search guidance for "user desktop files".

Acting on a user's linked machine (on explicit request):

    ud = primitives.computer.user_desktop.session()
    display(await ud.get_screenshot())
    await ud.act('Open the Downloads folder')

For a pure "look and tell me what's on my screen" request, capture the
screenshot and read it with `query_llm(prompt, images=[png_bytes])` — you do
not need `observe()` or `act()` for perception. A linked Mac left alone
shows its screensaver: treat that as a LOCKED machine, never as on-screen
content to describe (search guidance for "unlock macOS user desktop").

Viewing computer state in detail

    # Show the user a screenshot:
    display(await primitives.computer.desktop.get_screenshot())

    # Interpret a screen with the vision model:
    import io
    img = await primitives.computer.desktop.get_screenshot()
    buf = io.BytesIO(); img.save(buf, 'PNG')
    answer = await query_llm('Describe what is on this screen.',
                             images=[buf.getvalue()])

Observation space: screenshots from native sessions (desktop and visible
web) may be downscaled to a model-aware observation space before being
returned. `act()` uses the same observation space internally and scales
coordinates back up before dispatching to xdotool. If you call low-level
`click(x, y)`, the coordinates must match the pixel space of the screenshot
returned by `get_screenshot()` on that same session. `display()` and
`query_llm(images=...)` both fit images to observation space automatically.

Coordinate spaces, precisely:
- Desktop and visible web (web-vm): screenshots capture the full physical
  display in observation space (including browser chrome, address bar,
  taskbar, window decorations). Both share the same coordinate system.
- Headless web (`visible=False`): screenshots capture only the page
  viewport; coordinates are viewport-relative.
- To `session.click(x, y)` on a HEADLESS web session, read coordinates from
  `session.get_screenshot()` — never from
  `primitives.computer.desktop.get_screenshot()`. To click on the desktop or
  in a VISIBLE web session, read coordinates from the desktop or
  visible-session screenshot (same display space).
"""

_DURABLE_TASKS_CONTENT = """\
How to create, verify, arm, and run durable tasks — work that happens
later, repeatedly, or on future inbound events: schedules, recurring
cadences, communication and provider-event triggers, offline jobs.

Operative contract
- Create and edit through the text-driven mutation loop:
  `primitives.tasks.update(text)` handles ALL durable task mutations,
  including one-shot creates and field edits. Example:

      await primitives.tasks.update(
          'Create a live task named Weekly digest (marketing) with '
          'description Summarize the week and email it to Dana, '
          'repeating every Monday at 09:00 UTC.'
      )

- Armed vs draft: a task only fires while armed — `enabled=True` plus a
  resolved `schedule.start_at` or trigger. A draft NEVER fires:
  provider-event triggers are born in state `draft` and stay inert until
  enabled with resolved bindings. Say "live"/"armed" in the create text
  rather than leaving a draft.
- MANDATORY post-create verification: after every create, call
  `primitives.tasks.ask(...)` and confirm (1) the exact fields, (2) it
  is armed (`enabled=True`; provider trigger state not `draft`), and
  (3) trigger bindings resolved — a provider-event task needs a
  non-empty `provider_event_binding_id`; a communication trigger needs
  named senders resolved to contact ids. WORKAROUND (2026-08, retire
  once the Orchestra typed-POST bug is fixed): the typed `POST /tasks`
  route can 400 on provider-event creates, and the `update_task`
  fallback then writes a task whose trigger has NO binding — it looks
  created but can never be armed. Verification is the only guard.
- Verbatim copy: quoted task names, descriptions, and reference tokens
  (`Ref: TASK-…`) are matched exactly — copy them verbatim, including
  punctuation and parenthetical suffixes; creates reject duplicates,
  and verification and later lookups depend on the literal string.
- `primitives.tasks.execute(task_id)` runs one instance now: a
  contained child actor interprets the task; returns a steerable handle.

Task model and taxonomy
A definition row carries authored intent only; every wake is projected by
Orchestra into a `Tasks/Executions` run row, where run state and outcomes
live. `schedule` and `trigger` are mutually exclusive on one task.
- scheduled: `schedule.start_at` (ISO-8601) with no `repeat` and no
  `trigger` — a one-shot. After it runs it is disarmed and can never be
  re-armed; create a new task instead of re-running it.
- recurring: `schedule` plus `repeat` patterns (minutely/hourly for
  sub-daily intervals; daily/weekly/monthly/yearly for calendar
  cadences). The successor occurrence is projected by Orchestra when a
  run is marked running — recurrence is a ledger invariant, and the
  definition stays armed across runs.
- triggered (communication): `trigger.kind="communication"` names a
  `medium` (email/SMS/call/…) with optional `from_contact_ids` /
  `omit_contact_ids` filters and a `recurring` flag (True returns the
  task to the triggerable state after each completion).
- provider_event: `trigger.kind="provider_event"` binds a third-party
  trigger — `connection_id`, `backend_id`, `canonical_app_slug`,
  `provider_trigger_slug`, and `trigger_config` from the staged catalog
  schema, plus a `state` of draft|enabled|paused that is independent of
  `task.enabled`.
- offline is a delivery lane, not a task type: `offline=True` runs in
  the hidden headless lane without the live assistant runtime, so the
  run is not steerable from chat. Do not mark tasks offline unless
  asked. `requires_filesystem` / `requires_computer` independently hold
  the run until the synced Local workspace or a computer-use desktop is
  ready.
- `deadline` is a calendar due date; `start_at` is when work should
  begin; `max_runtime_seconds` bounds one attempt's wall clock. For
  short predictable work set only `start_at`. `priority` is
  low|normal|high|urgent; `tags` carry no scheduling semantics.
- `enabled=False` disarms everything: schedules and triggers do not
  activate, and manual execute is rejected until re-enabled.

Update semantics (`update_task`)
- Only provided fields change. `start_at`/`deadline`/`repeat`/`trigger`
  distinguish omitted from explicit None: None clears the field, and
  clearing the schedule sweeps `repeat` with it unless a new repeat is
  set in the same call. Convert scheduled→triggered in one call:
  `trigger=..., start_at=None`.
- Provider-event authored edits are revision-checked (`task_revision`)
  and cannot be mixed with runtime fields (e.g. `enabled`) in one call.
- Deployment-owned tasks (`custom_hash` set, deployment-managed) refuse
  runtime edits of authored fields — edit the bundle source and re-sync.
  A workflow-planted task is released to the user on the first authored
  edit and stops being reconciled.

Binding resolution in depth
- Communication triggers: resolve named senders to contact ids before
  creating — `from_contact_ids` is a list of contact ids, and a filter
  that never got resolved to ids cannot match. Unset matches any
  sender; `omit_contact_ids` overrides.
- Provider-event triggers: Orchestra manages a subscription lifecycle
  keyed by the task's stable `provider_event_binding_id` (required on
  every triggerable provider-event row). The composed lifecycle state is
  draft|connecting|active|recovering|paused|needs_attention|removing;
  `active` requires the task enabled, the authored trigger state
  `enabled`, healthy runtime, open local acceptance, and an active
  generation id. Inspect with `get_provider_trigger_health(task_id=...)`
  and drive with the pause/resume/retry provider-trigger tools.

Entrypoint vs description-driven execution
- Default to description-driven: `entrypoint=None` makes the task
  agentic — the due wake calls `primitives.tasks.execute(task_id=...)`
  and a contained child actor interprets the name, description, and
  metadata. Put the operative context into the description.
- Do not attach an untested entrypoint at creation. Entrypoint
  persistence should follow an explicit user request or a successful
  run reviewed as stable enough to store; offline promotion additionally
  requires separate certification.
- Stored entrypoints: prefer `async def` + `await`; never nest
  `asyncio.run(...)` (offline Jobs already own the loop — use
  `run_coro_sync` for a sync façade); keep expressive stdlib `logging`
  PHASE/SKIP/SOFT_FAIL trails so soft outcomes (empty results, skips,
  degraded fallbacks) leave evidence; focused `query_llm(...)` calls for
  bounded semantic judgment are fine.

Provider trigger catalog discovery
- `list_provider_trigger_connections(...)` shows active assistant-owned
  integration connections that can back provider triggers; then
  `list_provider_trigger_catalog(canonical_app_slug=..., limit=...,
  offset=...)` lists staged trigger slugs and config schemas for those
  connected apps, and `describe_provider_trigger(provider_trigger_slug=...,
  backend_id=...)` returns one trigger's full schema. An empty catalog
  usually means no matching connection yet, not that the provider lacks
  the trigger — connect the app first, then re-list.
- `list_provider_trigger_resources(...)` enumerates provider-side
  resources (channels, calendars, repos, …) for `trigger_config` values.

Execution guards (`execute`)
- Rejected: disabled tasks, one-shots that already ran, a task invoking
  its own task_id within its execution chain, and a wake targeting an
  instance that is already active. Concurrent instances of the same
  task_id from distinct wakes are allowed — serialize in the entrypoint
  if needed.
"""

_SHARING_LINKS_CONTENT = """\
How to read a OneDrive/SharePoint sharing link the user pastes — including
links shared from OUTSIDE their organization ("anyone with the link" and
cross-tenant shares).

Resolve the link through the Microsoft Graph shares API via the workspace
proxy. Never fetch the sharing URL itself, parse its HTML, or extract
page-embedded access grants — that route is fragile, leaks credential-like
material, and bypasses the user's file-access controls.

Procedure (inside `execute_code`, with the connected Microsoft workspace):

1. Encode the sharing URL into a share token:
   `share = "u!" + base64.urlsafe_b64encode(url.encode()).decode().rstrip("=")`
2. Resolve the item:
   `GET {MICROSOFT_GRAPH_BASE}/shares/{share}/driveItem`
   with `Authorization: Bearer {get_oauth_access_token("microsoft")}`.
   The response is a normal driveItem: `name`, `folder`/`file`, `id`, and
   `parentReference.driveId`.
3. Walk it like any other item:
   - children: `.../shares/{share}/driveItem/children`
   - a nested path: `.../shares/{share}/driveItem:/sub/folder:/children`
   - file bytes: `.../shares/{share}/driveItem:/sub/file.csv:/content`
   Or, after step 2, address it directly as
   `.../drives/{parentReference.driveId}/items/{id}` and descend from there.

What makes this non-obvious:

- The proxy sends `Prefer: redeemSharingLinkIfNecessary` on shares requests,
  which is the API equivalent of the user opening the link in a browser —
  without it, an anyone-with-the-link or cross-tenant share resolves to
  nothing even though the link "works" in a browser. On older runtimes that
  do not inject the header, set it yourself on every `/shares` request.
- Links shared with "anyone with the link" NEVER appear in `sharedWithMe`
  or the user's OneDrive UI until opened. Their absence from listings says
  nothing about access — resolve the link itself.
- If `/shares/{share}/driveItem` fails on an older runtime (403 on
  `/content`, or an unfollowable 308), fall back to the two-step form: read
  `/shares/{share}/driveItem` for `parentReference.driveId` + `id`, then use
  `/drives/{driveId}/items/{itemId}/...` for everything else.
- Google sharing links carry the file id in the URL; use
  `{GOOGLE_DRIVE_BASE}/files/{id}?supportsAllDrives=true` — no share-token
  step exists or is needed.

When a share will not resolve, identify the connected account before
retrying variations. `GET {MICROSOFT_GRAPH_BASE}/me` returns
`userPrincipalName` and `id`; a work/school (Entra) identity can resolve
another tenant's shares, a personal Microsoft account (MSA) generally
cannot, and `/sites/*` refuses outright for one with "This API is not
supported for MSA accounts". Two signatures point the same way: a redirect
the provider will not complete (reported as "redirected ... without saying
where to"), and `sharedWithMe` returning zero items where a share was
expected. If the account is an MSA, no request shape will fix it — say so
and ask for the workspace to be reconnected through the work/school flow,
or for the folder's `driveId` and `itemId` directly.

To then STORE what the share holds (spreadsheets into queryable tables,
documents into collections), download the files and hand them to
`primitives.ingestion.submit` — do not re-implement storage.
"""

PLATFORM_GUIDANCE_ENTRIES: Dict[str, Dict[str, str]] = {
    "platform/self-knowledge": {
        "title": "[platform] Answering questions about the Unify platform itself",
        "content": _PLATFORM_MAP_CONTENT,
    },
    "platform/workspace-sharing-links": {
        "title": "[platform] Reading OneDrive/SharePoint sharing links via the workspace",
        "content": _SHARING_LINKS_CONTENT,
    },
    "platform/integrations-envelopes": {
        "title": (
            "[platform] Integrating external apps: credentials, workspace "
            "OAuth proxy, result envelopes, and scopes"
        ),
        "content": _INTEGRATIONS_ENVELOPES_CONTENT,
    },
    "platform/manager-routing": {
        "title": (
            "[platform] Choosing between overlapping state managers: data vs "
            "files vs ingestion, workspace email vs comms"
        ),
        "content": _MANAGER_ROUTING_CONTENT,
    },
    "platform/desktop-procedures": {
        "title": (
            "[platform] Driving desktops and reading screens: your desktop "
            "vs a user's linked desktop, screenshots, coordinate spaces"
        ),
        "content": _DESKTOP_PROCEDURES_CONTENT,
    },
    "platform/macos-user-desktop-unlock": {
        "title": (
            "[platform] Unlock a locked macOS user desktop "
            "(screensaver / lock screen)"
        ),
        "content": _MACOS_UNLOCK_CONTENT,
    },
    "platform/user-desktop-files": {
        "title": (
            "[platform] User desktop files: read, pull, and sync a linked "
            "user's filesystem"
        ),
        "content": _USER_DESKTOP_FILES_CONTENT,
    },
    "platform/durable-tasks": {
        "title": (
            "[platform] Durable tasks: creating, verifying, arming, and "
            "running scheduled, triggered, and provider-event tasks"
        ),
        "content": _DURABLE_TASKS_CONTENT,
    },
}


def default_guidance_entries() -> Dict[str, Dict[str, str]]:
    """The full default seeding set: imported skills + platform entries."""
    return {**load_snapshot(), **PLATFORM_GUIDANCE_ENTRIES}


def stable_guidance_id(title: str) -> int:
    """Derive the stable builtin guidance id from a namespaced title.

    First 4 bytes of SHA-256, masked to the signed int32 range so backend
    integer sorting never overflows (mirrors primitive function ids).
    """
    digest = hashlib.sha256(title.encode("utf-8")).digest()
    return int.from_bytes(digest[:4], "big") & 0x7FFFFFFF


def entry_hash(title: str, content: str) -> str:
    """Content hash guarding per-skill reseeding."""
    return hashlib.sha256(f"{title}\x00{content}".encode("utf-8")).hexdigest()[:16]


def load_snapshot(path: Optional[Path] = None) -> Dict[str, Dict[str, str]]:
    """Load the committed builtins guidance snapshot (skill key → entry).

    Returns an empty mapping when the snapshot has not been generated yet.
    """
    path = path or SNAPSHOT_PATH
    if not path.exists():
        return {}
    data = json.loads(path.read_text(encoding="utf-8"))
    return data.get("skills", {})


def _ensure_catalog_storage(project: str) -> None:
    """Create the catalogue project and contexts (idempotent).

    The context is created without the per-assistant Guidance foreign keys
    (cross-project FKs do not exist); builtin entries have empty ``images``
    and ``function_ids``.
    """
    ensure_builtins_project(project)
    unisdk.create_context(
        BUILTINS_GUIDANCE_CONTEXT,
        description="Builtin procedural guidance imported from the Agent Skills ecosystem.",
        unique_keys={"guidance_id": "int"},
        project=project,
    )
    # Pre-create the model schema so federated reads (from_fields
    # projections) are well-defined even before the first rows land.
    unisdk.create_fields(
        model_to_fields(Guidance),
        context=BUILTINS_GUIDANCE_CONTEXT,
        project=project,
    )
    unisdk.create_context(
        BUILTINS_GUIDANCE_META_CONTEXT,
        description="Seeding state for the builtin guidance catalogue.",
        unique_keys={"meta_id": "int"},
        project=project,
    )


def _delete_rows_by_ids(project: str, guidance_ids: List[int]) -> None:
    if not guidance_ids:
        return
    ids_expr = ", ".join(str(gid) for gid in sorted(set(guidance_ids)))
    logs = unisdk.get_logs(
        project=project,
        context=BUILTINS_GUIDANCE_CONTEXT,
        filter=f"guidance_id in [{ids_expr}]",
        return_ids_only=True,
    )
    if logs:
        unisdk.delete_logs(
            project=project,
            context=BUILTINS_GUIDANCE_CONTEXT,
            logs=logs,
        )


def _guidance_diff(
    project: str,
    desired: Dict[str, Dict[str, object]],
) -> tuple[List[str], List[str], Dict[str, Dict[str, object]]]:
    """Read-only diff of the stored guidance hashes against *desired*.

    Returns ``(changed_keys, removed_keys, current)``. Reads only, so it runs
    for any principal that can read the public Builtins project. Raises when the
    catalogue storage is absent (fresh project).
    """
    current = read_seed_hashes(
        project,
        meta_context=BUILTINS_GUIDANCE_META_CONTEXT,
        key=_HASH_MAP_KEY,
    )
    changed = [
        skill_key
        for skill_key, state in desired.items()
        if (current.get(skill_key) or {}).get("hash") != state["hash"]
    ]
    removed = [skill_key for skill_key in current if skill_key not in desired]
    return changed, removed, current


def _insert_entries(project: str, entries: List[Dict[str, str]]) -> None:
    if not entries:
        return
    rows = [
        Guidance(
            guidance_id=stable_guidance_id(entry["title"]),
            title=entry["title"],
            content=entry["content"],
            is_builtin=True,
        ).model_dump(mode="json")
        for entry in entries
    ]
    unisdk.create_logs(
        project=project,
        context=BUILTINS_GUIDANCE_CONTEXT,
        entries=rows,
        recompute_derived=True,
    )


def seed_builtin_guidance(
    *,
    project: Optional[str] = None,
    entries: Optional[Dict[str, Dict[str, str]]] = None,
) -> bool:
    """Seed the global builtins guidance catalogue from the snapshot.

    Idempotent and hash-guarded per skill: only skills whose title/content
    changed (or disappeared from the snapshot) are deleted and re-inserted,
    with ``recompute_derived=True`` so embeddings recompute only for written
    rows. Always ensures the ``content`` and ``title`` vector columns exist
    when the catalogue has rows, so read-only consumers can run ranked
    semantic search without any write access.

    Returns True when any rows were written or removed, False when already
    up to date.
    """
    project = project or builtins_project()
    entries = entries if entries is not None else default_guidance_entries()
    desired = {
        skill_key: {
            "hash": entry_hash(entry["title"], entry["content"]),
            "guidance_id": stable_guidance_id(entry["title"]),
        }
        for skill_key, entry in entries.items()
    }

    logger.info(
        "Starting builtins guidance catalogue seed project=%s skills=%d",
        project,
        len(entries),
    )

    # Read-only convergence probe (see seed_builtin_primitives): public-read
    # Builtins lets any principal verify convergence; an already-seeded
    # catalogue is a no-op. A missing catalogue raises and falls through to the
    # owner seed path.
    try:
        changed_keys, removed_keys, current = _guidance_diff(project, desired)
        storage_ready = True
    except RequestError:
        storage_ready = False

    if storage_ready and not changed_keys and not removed_keys:
        logger.info(
            "Builtins guidance catalogue already converged project=%s skills=%d; "
            "read-only no-op",
            project,
            len(entries),
        )
        return False

    _ensure_catalog_storage(project)
    if not storage_ready:
        changed_keys, removed_keys, current = _guidance_diff(project, desired)

    if changed_keys or removed_keys:
        stale_ids = [
            (current.get(skill_key) or {}).get("guidance_id")
            for skill_key in changed_keys + removed_keys
        ]
        stale_ids = [gid for gid in stale_ids if gid is not None]
        stale_ids.extend(
            desired[skill_key]["guidance_id"] for skill_key in changed_keys
        )
        _delete_rows_by_ids(project, stale_ids)
        _insert_entries(project, [entries[skill_key] for skill_key in changed_keys])
        write_seed_hashes(
            project,
            desired,
            meta_context=BUILTINS_GUIDANCE_META_CONTEXT,
            key=_HASH_MAP_KEY,
        )
        logger.info(
            "Seeded builtins guidance project=%s changed=%d removed=%d",
            project,
            len(changed_keys),
            len(removed_keys),
        )
    else:
        logger.info(
            "Builtins guidance catalogue already up to date project=%s skills=%d; "
            "skipping row rewrites",
            project,
            len(entries),
        )

    if desired:
        logger.info("Ensuring builtins guidance embedding columns project=%s", project)
        ensure_vector_column(
            BUILTINS_GUIDANCE_CONTEXT,
            embed_column="_content_emb",
            source_column="_content_head",
            derived_expr=f"str({{content}})[:{CONTENT_EMBED_HEAD_CHARS}]",
            project=project,
        )
        ensure_vector_column(
            BUILTINS_GUIDANCE_CONTEXT,
            embed_column="_title_emb",
            source_column="title",
            project=project,
        )
    return bool(changed_keys or removed_keys)


__all__ = [
    "BUILTINS_GUIDANCE_CONTEXT",
    "BUILTINS_GUIDANCE_META_CONTEXT",
    "PLATFORM_GUIDANCE_ENTRIES",
    "SNAPSHOT_PATH",
    "default_guidance_entries",
    "entry_hash",
    "load_snapshot",
    "seed_builtin_guidance",
    "stable_guidance_id",
]
