from __future__ import annotations

from typing import Any, Dict, List, Optional, Union, TYPE_CHECKING

import unify

from unity.file_manager.types.file import FileRecordRow

if TYPE_CHECKING:
    from unity.file_manager.types.file import FileContentRow


def safe(self):
    return getattr(self, "safe") if hasattr(self, "safe") else (lambda x: x)


def _per_file_root(self) -> str:
    base = None
    try:
        _base_attr = getattr(self, "_per_file_root")
        if isinstance(_base_attr, str) and _base_attr:
            base = _base_attr
    except Exception:
        base = None
    if base is None:
        try:
            ctx = getattr(self, "_ctx")
            if isinstance(ctx, str) and "/FileRecords/" in ctx:
                prefix, alias = ctx.split("/FileRecords/", 1)
                base = f"{prefix}/Files/{alias}"
        except Exception:
            base = None
    return base or "Files"


# ---------- FileRecords root (FileRecords/<alias>) helpers ---------------------


def add_or_replace_file_row(
    self,
    *,
    entry: Dict[str, Any],
) -> Dict[str, Any]:
    """
    Create or replace a file row in the FileRecords/<alias> context.

    Delegates Unify operations to DataManager.

    Returns a short outcome dict.
    """
    dm = self._data_manager

    # Try to find an existing row by file_path; replace if found
    fp = entry.get("file_path")
    if fp:
        rows = dm.filter(
            context=self._ctx,
            filter=f"file_path == {fp!r}",
            limit=2,
            columns=["file_id", "file_path"],
        )

        if len(rows) > 1:
            raise ValueError(
                f"Multiple index rows found for file_path {fp!r} (data integrity)",
            )
        if len(rows) == 1:
            # Update existing row via DataManager
            file_id = rows[0].get("file_id")
            dm.update_rows(
                context=self._ctx,
                updates=entry,
                filter=f"file_id == {file_id}",
            )
            return {
                "outcome": "file updated successfully",
                "details": {
                    "file_id": file_id,
                    "file_path": fp,
                },
            }

    # Create new row via DataManager
    dm.insert_rows(
        context=self._ctx,
        rows=[entry],
        add_to_all_context=self.include_in_multi_assistant_table,
    )
    # Note: file_id is auto-generated by the backend
    return {
        "outcome": "file created successfully",
        "details": {
            "file_id": entry.get("file_id"),  # May be None if auto-generated
            "file_path": entry.get("file_path"),
        },
    }


def delete_file_rows_by_ids(
    self,
    *,
    log_ids: List[int],
) -> Dict[str, Any]:
    """
    DEPRECATED: Use DataManager.delete_rows() with a filter instead.

    Delete file rows by their internal log IDs.

    Note: This function is deprecated because DataManager operates on
    filter expressions, not raw log IDs. For new code, use:
        dm.delete_rows(context=..., filter="file_id == X")
    """
    import warnings

    warnings.warn(
        "delete_file_rows_by_ids() is deprecated. Use DataManager.delete_rows() with filter instead.",
        DeprecationWarning,
        stacklevel=2,
    )

    if not log_ids:
        return {"status": "no-op"}

    # Fall back to direct unify call since DataManager doesn't support log_id-based deletion
    return unify.delete_logs(
        logs=list(log_ids),
        context=self._ctx,
        project=unify.active_project(),
        delete_empty_logs=True,
    )


def rename_file_contexts(
    self,
    *,
    old_file_path: str,
    new_file_path: str,
) -> Dict[str, Any]:
    """
    DEPRECATED: This function is no longer needed.

    Since context paths now use stable file_id identifiers instead of file_path,
    renaming/moving a file does NOT require renaming contexts. Only the FileRecords
    row needs to be updated with the new file_path.

    This function is kept for backward compatibility but returns a no-op result.

    Old behavior (file_path-based contexts):
    - per_file: rename <base>/Files/<alias>/<safe(old)>/Content → <base>/Files/<alias>/<safe(new)>/Content
    - Tables contexts were also renamed

    New behavior (file_id-based contexts):
    - Contexts use stable file_id: <base>/Files/<alias>/<file_id>/Content
    - No context rename needed on file rename/move
    - Only FileRecords row is updated with new file_path, file_name, source_uri

    Returns
    -------
    dict
        {"renamed": {"content": 0, "tables": 0}, "_deprecated": True}
    """
    import warnings

    warnings.warn(
        "rename_file_contexts() is deprecated: context paths now use stable file_id, "
        "no context rename needed. Only update FileRecords row.",
        DeprecationWarning,
        stacklevel=2,
    )

    return {"renamed": {"content": 0, "tables": 0}, "_deprecated": True}


def update_file_record_by_path(
    self,
    *,
    old_file_path: str,
    new_file_path: str,
    **extra_updates: Any,
) -> Dict[str, Any]:
    """
    Update the FileRecords row identified by old_file_path to the new_file_path,
    applying any extra field updates (e.g., file_name, display_path, source_uri).

    Delegates to DataManager for Unify operations.
    """
    # Use DataManager for Unify operations
    dm = self._data_manager

    # Find the existing row
    rows = dm.filter(
        context=self._ctx,
        filter=f"file_path == {old_file_path!r}",
        limit=2,
        columns=["file_id", "file_path"],
    )

    if not rows:
        return {"outcome": "no-op", "reason": "not found"}
    if len(rows) > 1:
        raise ValueError(f"Multiple rows found for file_path={old_file_path!r}")

    file_id = rows[0].get("file_id")

    # Build updates
    updates = {"file_path": new_file_path}
    updates.update(extra_updates or {})

    # Update via DataManager
    dm.update_rows(
        context=self._ctx,
        updates=updates,
        filter=f"file_id == {file_id}",
    )

    return {
        "outcome": "updated",
        "details": {
            "file_id": file_id,
            "file_path": new_file_path,
        },
    }


def delete_file_contexts(
    self,
    *,
    file_id: int,
    file_path: Optional[str] = None,
) -> Dict[str, Any]:
    """
    Delete all contexts and rows associated with a file according to its ingest layout.

    Since context paths now use stable file_id identifiers, this function uses file_id
    to construct context paths for deletion.

    Delegates Unify operations to DataManager.

    Parameters
    ----------
    file_id : int
        The stable file_id from FileRecords index.
    file_path : str | None
        Optional file_path for resolving ingest mode. If not provided, defaults to per_file mode.

    - per_file: drop the per-file Content context and all per-file Tables contexts.
      Context paths: Files/<alias>/<file_id>/Content, Files/<alias>/<file_id>/Tables/*
    - unified: do not drop the unified Content context; delete only rows in that
      context where file_id matches; drop this file's per-file Tables contexts if present.
    """
    from .storage import _resolve_file_target as _res

    dm = self._data_manager
    base = _per_file_root(self)

    purged = {"content": 0, "content_rows": 0, "tables": 0}

    # Resolve ingest mode from file record or provided path
    ingest_mode = "per_file"  # default
    unified_label = None
    table_ingest = True

    if file_path:
        try:
            info = _res(self, file_path)
            ingest_mode = info.get("ingest_mode", "per_file")
            unified_label = info.get("unified_label")
        except Exception:
            pass

    # Get table_ingest setting from file record
    try:
        rows = dm.filter(
            context=self._ctx,
            filter=f"file_id == {file_id}",
            limit=1,
            columns=["table_ingest"],
        )
        if rows:
            table_ingest = bool(rows[0].get("table_ingest", True))
    except Exception:
        pass

    if ingest_mode == "per_file":
        # Context paths use file_id: Files/<alias>/<file_id>/Content
        content_ctx = f"{base}/{file_id}/Content"
        try:
            dm.delete_table(content_ctx, dangerous_ok=True)
            purged["content"] += 1
        except Exception:
            pass

        # Delete all Tables contexts for this file_id
        if table_ingest:
            tables_prefix = f"{base}/{file_id}/Tables/"
            try:
                all_tables = dm.list_tables(prefix=tables_prefix)
                for tctx in all_tables:
                    try:
                        dm.delete_table(tctx, dangerous_ok=True)
                        purged["tables"] += 1
                    except Exception:
                        pass
            except Exception:
                pass
    else:
        # unified: delete only rows with matching file_id from unified Content
        _safe = safe(self)
        uctx = f"{base}/{_safe(str(unified_label or 'Unified'))}/Content"
        try:
            deleted = dm.delete_rows(
                context=uctx,
                filter=f"file_id == {file_id}",
            )
            purged["content_rows"] += deleted
        except Exception:
            pass

        # Delete per-file Tables contexts (unified mode still has per-file tables)
        if table_ingest:
            tables_prefix = f"{base}/{file_id}/Tables/"
            try:
                all_tables = dm.list_tables(prefix=tables_prefix)
                for tctx in all_tables:
                    try:
                        dm.delete_table(tctx, dangerous_ok=True)
                        purged["tables"] += 1
                    except Exception:
                        pass
            except Exception:
                pass

    return {"purged": purged}


def per_file_table_ctx(self, *, file_path: str, table: str) -> str:
    """Compatibility wrapper → storage.ctx_for_file_table."""
    from .storage import ctx_for_file_table as _ctx

    return _ctx(self, file_path=file_path, table=table)


def per_file_ctx(self, *, file_path: str) -> str:
    """Compatibility wrapper → storage.ctx_for_file."""
    from .storage import ctx_for_file as _ctx

    return _ctx(self, file_path=file_path)


def ensure_per_file_context(
    self,
    *,
    file_path: str,
) -> None:
    """Compatibility wrapper → storage.ensure_file_context."""
    from .storage import ensure_file_context as _ensure

    _ensure(self, file_path=file_path)


def ensure_per_file_table_context(
    self,
    *,
    file_path: str,
    table: str,
    unique_key: str = "row_id",
    auto_counting: Optional[Dict[str, Optional[str]]] = None,
    columns: Optional[List[str]] = None,
    example_row: Optional[Dict[str, Any]] = None,
    business_context: Optional[Any] = None,
) -> None:
    """Compatibility wrapper → storage.ensure_file_table_context."""
    from .storage import ensure_file_table_context as _ensure_tbl

    _ensure_tbl(
        self,
        file_path=file_path,
        table=table,
        unique_key=unique_key,
        business_context=business_context,
        auto_counting=auto_counting,
        columns=columns,
        example_row=example_row,
    )


def delete_per_file_table_rows_by_filter(
    self,
    *,
    file_path: str,
    table: str,
    filter_expr: Optional[str],
) -> int:
    """Delete rows from a per-file table context.

    Delegates to DataManager for Unify operations.
    """
    dm = self._data_manager
    ctx = per_file_table_ctx(self, file_path=file_path, table=table)

    if filter_expr is None:
        # Delete all rows - count first then delete
        rows = dm.filter(context=ctx, limit=10000, columns=["file_id"])
        if not rows:
            return 0
        # Delete all via a filter that matches everything
        return dm.delete_rows(context=ctx, filter="1 == 1")
    else:
        return dm.delete_rows(context=ctx, filter=filter_expr)


def batch_insert_per_file_table_rows(
    self,
    *,
    file_path: str,
    table: str,
    rows: List[Dict[str, Any]],
) -> List[int]:
    """Insert rows into a per-file table context.

    Delegates to DataManager for Unify operations.

    Returns list of inserted count (DataManager doesn't return log IDs).
    """
    if not rows:
        return []
    dm = self._data_manager
    ctx = per_file_table_ctx(self, file_path=file_path, table=table)
    count = dm.insert_rows(
        context=ctx,
        rows=rows,
        add_to_all_context=self.include_in_multi_assistant_table,
    )
    # DataManager returns count, not IDs - return empty list for backward compat
    return list(range(count)) if count else []


def delete_per_file_rows_by_filter(
    self,
    *,
    file_path: str,
    filter_expr: Optional[str],
) -> int:
    """Delete rows from a per-file Content context.

    Delegates to DataManager for Unify operations.
    """
    dm = self._data_manager
    ctx = per_file_ctx(self, file_path=file_path)

    if filter_expr is None:
        # Delete all rows
        return dm.delete_rows(context=ctx, filter="1 == 1")
    else:
        return dm.delete_rows(context=ctx, filter=filter_expr)


def batch_insert_per_file_rows(
    self,
    *,
    file_path: str,
    rows: List[Dict[str, Any]],
) -> List[int]:
    """Insert rows into a per-file Content context.

    Delegates to DataManager for Unify operations.

    Returns list of inserted count (DataManager doesn't return log IDs).
    """
    if not rows:
        return []
    dm = self._data_manager
    ctx = per_file_ctx(self, file_path=file_path)
    count = dm.insert_rows(
        context=ctx,
        rows=rows,
        add_to_all_context=self.include_in_multi_assistant_table,
    )
    # DataManager returns count, not IDs - return empty list for backward compat
    return list(range(count)) if count else []


# ---------- High-level create helpers (ensure + insert) ------------------------


def create_file_record(
    self,
    *,
    entry: FileRecordRow,
) -> Dict[str, Any]:
    """Create or update a FileRecord row in the global index (idempotent)."""
    return add_or_replace_file_row(
        self,
        entry=entry.model_dump(mode="json", exclude_none=True),
    )


def create_file_content(
    self,
    *,
    file_path: str,
    rows: List["FileContentRow"],
) -> List[int]:
    """Ensure per-file context then insert rows (batched)."""
    from unity.file_manager.types.file import FileContentRow

    ensure_per_file_context(
        self,
        file_path=file_path,
    )
    entries: List[Dict[str, Any]] = [
        (
            r.model_dump(mode="json", exclude_none=True)
            if isinstance(r, FileContentRow)
            else dict(r)
        )  # type: ignore[arg-type]
        for r in list(rows or [])
    ]
    return batch_insert_per_file_rows(self, file_path=file_path, rows=entries)


def create_file_table(
    self,
    *,
    file_path: str,
    table: str,
    rows: List[Dict[str, Any]],
    columns: Optional[List[str]] = None,
    example_row: Optional[Dict[str, Any]] = None,
) -> List[int]:
    """Ensure per-file table context (with fields) then insert rows (batched)."""
    ensure_per_file_table_context(
        self,
        file_path=file_path,
        table=table,
        columns=columns,
        example_row=example_row,
    )
    return batch_insert_per_file_table_rows(
        self,
        file_path=file_path,
        table=table,
        rows=rows,
    )


# ----------------------------- Mutator helpers ------------------------------- #


def rename_file(
    self,
    *,
    file_id_or_path: Union[str, int],
    new_name: str,
) -> Dict[str, Any]:
    """Rename a file via adapter and update FileRecords index.

    Since context paths use stable file_id identifiers, no context rename is needed.
    Only the FileRecords row is updated with the new file_path, file_name, source_uri.

    Delegates Unify operations to DataManager.

    Parameters
    ----------
    file_id_or_path : str | int
        Either the file_id (int) as preserved in the FileRecords index, or the
        fully-qualified file_path (str) as stored in the FileRecords index/context.
        When a file_id is provided, it is resolved to the corresponding file_path.
    new_name : str
        New file name; adapter determines path semantics.
    """
    if not getattr(self._adapter.capabilities, "can_rename", False):  # type: ignore[attr-defined]
        raise PermissionError("Rename not permitted by backend policy")

    dm = self._data_manager
    file_id: Optional[int] = None

    # Resolve file_id_or_path to file_path and file_id using DataManager
    if isinstance(file_id_or_path, int):
        file_id = file_id_or_path
        rows = dm.filter(
            context=self._ctx,
            filter=f"file_id == {file_id}",
            limit=1,
            columns=["file_id", "file_path", "source_uri"],
        )
        if not rows:
            raise ValueError(f"No file found with file_id {file_id}")
        file_path = rows[0].get("file_path")
        if not file_path:
            raise ValueError(f"File record with file_id {file_id} has no file_path")
        file_path = str(file_path)
    else:
        file_path = str(file_id_or_path)
        rows = dm.filter(
            context=self._ctx,
            filter=f"file_path == {file_path!r}",
            limit=2,
            columns=["file_id", "file_path", "source_uri"],
        )
        if not rows:
            raise ValueError(f"File '{file_path}' not found in index.")
        if len(rows) > 1:
            raise ValueError(
                f"Multiple files found with file_path '{file_path}'. Data integrity issue.",
            )
        file_id = rows[0].get("file_id")

    new_name = str(new_name)
    old_file_path = rows[0].get("file_path", file_path)
    old_source_uri = rows[0].get("source_uri", "")

    # Perform filesystem rename via adapter
    ref = self._adapter.rename(old_file_path, new_name)  # type: ignore[attr-defined]
    new_path = ref.path

    # Update FileRecords row with new path info (no context rename needed)
    # Contexts use stable file_id, so they remain unchanged
    sync_errors = []
    try:
        # Compute new source_uri by replacing the filename in the old source_uri
        new_source_uri = old_source_uri
        if old_source_uri:
            # Replace old filename with new filename in source_uri
            old_name = (
                old_file_path.rsplit("/", 1)[-1]
                if "/" in old_file_path
                else old_file_path
            )
            if old_name in old_source_uri:
                new_source_uri = old_source_uri.replace(old_name, new_name)

        dm.update_rows(
            context=self._ctx,
            updates={
                "file_path": new_path,
                "file_name": new_name,
                "source_uri": new_source_uri,
            },
            filter=f"file_id == {file_id}",
        )
    except Exception as e:
        sync_errors.append(("index_update", str(e)))

    result = getattr(ref, "model_dump", lambda: {"path": ref.path, "name": new_name})()
    if sync_errors:
        result["_sync_warnings"] = sync_errors

    return result


def move_file(
    self,
    *,
    file_id_or_path: Union[str, int],
    new_parent_path: str,
) -> Dict[str, Any]:
    """Move a file via adapter and update FileRecords index.

    Since context paths use stable file_id identifiers, no context rename is needed.
    Only the FileRecords row is updated with the new file_path, file_name (if changed),
    and source_uri.

    Delegates Unify operations to DataManager.

    Parameters
    ----------
    file_id_or_path : str | int
        Either the file_id (int) as preserved in the FileRecords index, or the
        fully-qualified file_path (str) as stored in the FileRecords index/context.
        When a file_id is provided, it is resolved to the corresponding file_path.
    new_parent_path : str
        Destination directory in adapter-native form.
    """
    if not getattr(self._adapter.capabilities, "can_move", False):  # type: ignore[attr-defined]
        raise PermissionError("Move not permitted by backend policy")

    dm = self._data_manager
    file_id: Optional[int] = None

    # Resolve file_id_or_path to file_path and file_id using DataManager
    if isinstance(file_id_or_path, int):
        file_id = file_id_or_path
        rows = dm.filter(
            context=self._ctx,
            filter=f"file_id == {file_id}",
            limit=1,
            columns=["file_id", "file_path", "file_name", "source_uri"],
        )
        if not rows:
            raise ValueError(f"No file found with file_id {file_id}")
        file_path = rows[0].get("file_path")
        if not file_path:
            raise ValueError(f"File record with file_id {file_id} has no file_path")
        file_path = str(file_path)
    else:
        file_path = str(file_id_or_path)
        rows = dm.filter(
            context=self._ctx,
            filter=f"file_path == {file_path!r}",
            limit=2,
            columns=["file_id", "file_path", "file_name", "source_uri"],
        )
        if not rows:
            raise ValueError(f"File '{file_path}' not found in index.")
        if len(rows) > 1:
            raise ValueError(
                f"Multiple files found with file_path '{file_path}'. Data integrity issue.",
            )
        file_id = rows[0].get("file_id")

    new_parent_path = str(new_parent_path)
    old_file_path = rows[0].get("file_path", file_path)
    old_file_name = rows[0].get("file_name", "")
    old_source_uri = rows[0].get("source_uri", "")

    # Perform filesystem move via adapter
    ref = self._adapter.move(old_file_path, new_parent_path)  # type: ignore[attr-defined]
    new_path = ref.path

    # Extract new file name from the new path (move might change the name too)
    new_file_name = new_path.rsplit("/", 1)[-1] if "/" in new_path else new_path

    # Update FileRecords row with new path info (no context rename needed)
    # Contexts use stable file_id, so they remain unchanged
    sync_errors = []
    try:
        # Compute new source_uri by replacing the directory path
        new_source_uri = old_source_uri
        if old_source_uri and old_file_path:
            # Replace old path with new path in source_uri
            old_dir = old_file_path.rsplit("/", 1)[0] if "/" in old_file_path else ""
            new_dir = new_parent_path.rstrip("/")
            if old_dir and old_dir in old_source_uri:
                new_source_uri = old_source_uri.replace(old_dir, new_dir)

        updates: Dict[str, Any] = {
            "file_path": new_path,
            "source_uri": new_source_uri,
        }
        # Update file_name if it changed (move can also rename)
        if new_file_name != old_file_name:
            updates["file_name"] = new_file_name

        dm.update_rows(
            context=self._ctx,
            updates=updates,
            filter=f"file_id == {file_id}",
        )
    except Exception as e:
        sync_errors.append(("index_update", str(e)))

    result = getattr(
        ref,
        "model_dump",
        lambda: {"path": ref.path, "parent": new_parent_path},
    )()
    if sync_errors:
        result["_sync_warnings"] = sync_errors

    return result


def delete_file(
    self,
    *,
    file_id_or_path: Union[str, int],
    _log_id: Optional[int] = None,
) -> Dict[str, Any]:
    """Delete a file record and its contexts per ingest-mode rules.

    Delegates Unify operations to DataManager.

    Parameters
    ----------
    file_id_or_path : str | int
        Either the file_id (int) as preserved in the FileRecords index, or the
        fully-qualified file_path (str) as stored in the FileRecords index/context.
        When a file_id is provided, it is resolved to the corresponding file_path.
    _log_id : int | None
        DEPRECATED: This parameter is no longer used. Kept for backward compatibility.
    """
    dm = self._data_manager

    # Resolve file_id_or_path to file_path and file_id using DataManager
    if isinstance(file_id_or_path, int):
        file_id = file_id_or_path
        rows = dm.filter(
            context=self._ctx,
            filter=f"file_id == {file_id}",
            limit=1,
            columns=["file_id", "file_path"],
        )
        if not rows:
            raise ValueError(f"No file found with file_id {file_id}")
        file_path = rows[0].get("file_path", "")
        if not file_path:
            raise ValueError(f"File record with file_id {file_id} has no file_path")
        file_path = str(file_path)
    else:
        file_path = str(file_id_or_path)
        rows = dm.filter(
            context=self._ctx,
            filter=f"file_path == {file_path!r}",
            limit=2,
            columns=["file_id", "file_path"],
        )
        if not rows:
            raise ValueError(f"File '{file_path}' not found in index.")
        if len(rows) > 1:
            raise ValueError(
                f"Multiple files found with file_path '{file_path}'. Data integrity issue.",
            )
        file_id = rows[0].get("file_id")
        if file_id is None:
            raise ValueError(f"File record for '{file_path}' has no file_id")

    # Check if file is protected
    if getattr(self, "is_protected")(file_path):  # type: ignore[attr-defined]
        raise PermissionError(
            f"'{file_path}' is protected and cannot be deleted by FileManager.",
        )

    sync_errors = []

    # 1) Adapter deletion when supported (filesystem operation)
    if getattr(self, "_adapter", None) is not None and getattr(
        self._adapter.capabilities,
        "can_delete",
        False,
    ):
        try:
            self._adapter.delete(file_path)  # type: ignore[attr-defined]
        except (NotImplementedError, FileNotFoundError):
            pass
        except Exception as e:
            sync_errors.append(("adapter_delete", str(e)))

    # 2) Ingest-aware purge of contexts/rows via DataManager
    try:
        delete_file_contexts(self, file_id=file_id, file_path=file_path)
    except Exception as e:
        sync_errors.append(("context_delete", str(e)))

    # 3) Delete FileRecords index row via DataManager
    try:
        dm.delete_rows(
            context=self._ctx,
            filter=f"file_id == {file_id}",
        )
    except Exception as e:
        raise ValueError(f"Failed to delete file record: {e}")

    result: Dict[str, Any] = {
        "outcome": "file deleted",
        "details": {"file_id": file_id, "file_path": file_path},
    }
    if sync_errors:
        result["_sync_warnings"] = sync_errors

    return result
