name: Lint

on:
  push:
    branches:
    - '**'

jobs:
  black:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6

    - name: Set up Python
      uses: actions/setup-python@v6

    - name: Install pre-commit
      run: pip install pre-commit

    - name: Run black via pre-commit
      run: pre-commit run black --all-files --show-diff-on-failure
